const fs=require('fs'),path=require('path');
const root=process.cwd();
const sel=path.join(root,'src','selected');
if(!fs.existsSync(sel)) throw new Error('src/selected not found. Run this from the WOMATE project root.');
const markSrc=path.join(__dirname,'assets','womate-mark.png');
const markDir=path.join(root,'public','assets','img'); fs.mkdirSync(markDir,{recursive:true});
fs.copyFileSync(markSrc,path.join(markDir,'womate-selected-mark.png'));
const files=['selectedCard.css','SelectedCard.jsx','selectedCardRenderer.js','selectedStandalone.jsx'].map(x=>path.join(sel,x)).filter(fs.existsSync);
for(const f of files){let s=fs.readFileSync(f,'utf8');
  s=s.replaceAll('#17382b','#0E4D4A').replaceAll('#17382B','#0E4D4A')
     .replaceAll('#CAFF58','#C6FF52').replaceAll('#caff58','#C6FF52')
     .replaceAll('#F4F1E8','#F9F6FF').replaceAll('#f4f1e8','#F9F6FF')
     .replaceAll('#10231b','#083F3E').replaceAll('#10231B','#083F3E')
     .replaceAll('Share your selection. Carry the mission.','Driving inclusive climate action with technology.')
     .replaceAll('SHARE YOUR SELECTION. CARRY THE MISSION.','DRIVING INCLUSIVE CLIMATE ACTION WITH TECHNOLOGY.');
  fs.writeFileSync(f,s,'utf8');
}
// Add a safe enhancement module to the standalone page: caption + hashtags + card mark overlay.
const enh=path.join(sel,'selectedBrandEnhancements.js');
fs.writeFileSync(enh,`import './selectedBrandEnhancements.css';\n\nconst TAGS='#WOMATE #SheLeads #SheLeads2026 #WomenInClimate #ClimateLeadership #WomenLeadingClimateAction #AfricanWomenInClimate #ClimateAction #InclusiveClimateAction';\nfunction valByLabel(label){const els=[...document.querySelectorAll('input')]; const x=els.find(el=>{const p=el.closest('label,div');return p&&p.textContent.toLowerCase().includes(label.toLowerCase())});return x?.value?.trim()||''}\nfunction learnerName(){return valByLabel('full name')||valByLabel('name')||''}\nfunction caption(){const n=learnerName();return \`${'${n?`${n} — `:""}'}I’m excited to share that I have been selected for the She Leads Climate Mentorship Programme — Cohort 2 by WOMATE.\\n\\nOver the coming weeks, I’ll be strengthening my climate knowledge, leadership and capacity to turn learning into meaningful action.\\n\\nI’m looking forward to learning, connecting and contributing alongside an incredible community of emerging women climate leaders across Africa.\\n\\nDriving inclusive climate action with technology.\`;}\nfunction copy(t,b){navigator.clipboard?.writeText(t).then(()=>{const old=b.textContent;b.textContent='Copied';setTimeout(()=>b.textContent=old,1600)});}\nfunction mount(){if(document.querySelector('.selected-share-kit'))return; const host=document.querySelector('main')||document.body; const box=document.createElement('section');box.className='selected-share-kit';box.innerHTML=\`<div class="selected-share-eyebrow">READY TO SHARE</div><h2>Suggested caption</h2><p class="selected-share-note">Make it yours before you post.</p><div class="selected-caption-text"></div><div class="selected-share-actions"><button type="button" class="selected-copy-caption">Copy caption</button></div><h3>Suggested hashtags</h3><div class="selected-hashtags"></div><div class="selected-share-actions"><button type="button" class="selected-copy-tags">Copy hashtags</button></div></section>\`;host.appendChild(box);const ct=box.querySelector('.selected-caption-text'),ht=box.querySelector('.selected-hashtags');ct.textContent=caption();ht.textContent=TAGS;box.querySelector('.selected-copy-caption').onclick=e=>copy(caption(),e.currentTarget);box.querySelector('.selected-copy-tags').onclick=e=>copy(TAGS,e.currentTarget);document.addEventListener('input',()=>ct.textContent=caption());}\nif(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,250));else setTimeout(mount,250);\n`, 'utf8');
fs.writeFileSync(path.join(sel,'selectedBrandEnhancements.css'),`.selected-share-kit{max-width:1180px;margin:28px auto 64px;padding:32px;border-radius:28px;background:#F9F6FF;color:#083F3E;border:1px solid rgba(14,77,74,.14);box-shadow:0 18px 50px rgba(8,63,62,.08)}.selected-share-eyebrow{font-size:.75rem;font-weight:800;letter-spacing:.14em;color:#0E4D4A}.selected-share-kit h2{font-size:clamp(1.7rem,3vw,2.5rem);margin:.35rem 0 .25rem}.selected-share-kit h3{margin:1.6rem 0 .6rem}.selected-share-note{color:#526966;margin:0 0 1.25rem}.selected-caption-text,.selected-hashtags{white-space:pre-wrap;background:#fff;border:1px solid rgba(14,77,74,.12);border-radius:20px;padding:20px;line-height:1.7}.selected-hashtags{color:#0E4D4A;font-weight:650}.selected-share-actions{display:flex;justify-content:flex-end;margin-top:12px}.selected-share-actions button{border:0;border-radius:999px;padding:12px 18px;background:#0E4D4A;color:#fff;font-weight:800;cursor:pointer}.selected-share-actions button:hover{background:#083F3E}.selected-share-actions button:focus-visible{outline:3px solid #C6FF52;outline-offset:3px}@media(max-width:640px){.selected-share-kit{margin:20px 16px 40px;padding:22px;border-radius:22px}.selected-share-actions{justify-content:stretch}.selected-share-actions button{width:100%}}\n`,'utf8');
// Import enhancement once.
const stand=path.join(sel,'selectedStandalone.jsx'); if(fs.existsSync(stand)){let s=fs.readFileSync(stand,'utf8');if(!s.includes('selectedBrandEnhancements')){s=`import './selectedBrandEnhancements.js';\n`+s;fs.writeFileSync(stand,s,'utf8')}}
console.log('UPDATED: WOMATE /selected brand palette, tagline, favicon asset and share-caption kit.');
console.log('Brand: #0E4D4A / #C6FF52 / #F9F6FF / #083F3E');
console.log('Asset: /assets/img/womate-selected-mark.png');
console.log('NOTE: The existing card renderer was preserved; palette/tagline references were updated safely.');
