import React,{useState,useEffect}from'react';
import{createRoot}from'react-dom/client';
import{ArrowUpRight,Menu,X,ChevronRight,Leaf,Users,Award,Microscope,Quote,Sparkles,ShieldCheck,Brain,MoveRight,Play,Heart,Radio,Globe2}from'lucide-react';
import'./style.css';

const pages={
'/':{k:'WOMATE',title:'African women leading climate action.',accent:'Knowledge. Technology. Community.',intro:'We equip African women to understand climate systems, lead resilient communities and shape the institutions building our shared future.',type:'home'},
'/she-leads':{k:'SHE LEADS',title:'She Leads Climate Mentorship.',accent:'Climate knowledge. Leadership. Agency.',intro:'A learning and leadership pathway designed for young African women ready to move from climate concern to credible action.',type:'she'},
'/wok-action':{k:'WOK—ACTION',title:'Women’s local knowledge for climate adaptation.',accent:'Knowledge held by women is climate infrastructure.',intro:'We document, protect and activate women’s community knowledge as living evidence for locally grounded adaptation.',type:'wok'},
'/circle':{k:'THE WOMATE CIRCLE',title:'A climate community for women.',accent:'Belong. Build. Lead.',intro:'A professional and community network where women access opportunities, peers, learning, visibility and long-term climate leadership support.',type:'circle'},
'/research':{k:'RESEARCH',title:'We Research. You Lead.',accent:'Evidence built for better climate decisions.',intro:'Gender-responsive climate intelligence, programme design and evidence support for institutions working across Africa.',type:'research'},
'/resilient-minds':{k:'RESILIENT MINDS',title:'To See What Is Hidden.',accent:'Climate resilience must include mental health.',intro:'Support, research and care pathways addressing the emotional and psychological costs of climate disruption.',type:'minds'},
'/honours':{k:'CLIMATE HONOURS',title:'Amplify the Untold.',accent:'Recognising women moving Africa’s climate future forward.',intro:'An annual platform documenting, celebrating and connecting women whose climate leadership deserves to be seen.',type:'honours'},
'/leadership':{k:'LEADERSHIP',title:'Driving Inclusive Climate Action with Technology.',accent:'Women-led. Africa-rooted. Future-facing.',intro:'A multidisciplinary leadership team connecting climate science, technology, research, community practice and storytelling.',type:'leadership'},
'/funding':{k:'FUNDING SUPPORT',title:'Grant Application Support Programme 2026',accent:'Make strong climate work easier to fund.',intro:'Structured application support for African women founders building credible, investable and grant-ready climate initiatives.',type:'funding'},
'/womateer':{k:'WOMATEER',title:'Elevate Your Impact as a WOMATEER',accent:'Volunteer talent. Serious climate impact.',intro:'Contribute professional skill to a women-led climate organisation building knowledge, visibility and resilience across Africa.',type:'volunteer'},
'/merchandise':{k:'THE VAULT',title:'Wear the work.',accent:'WOMATE objects for climate community.',intro:'Limited pieces that carry the identity, conversations and conviction of women leading climate action.',type:'merch'}
};
const nav=[['She Leads','/she-leads'],['WoK-Action','/wok-action'],['Circle','/circle'],['Research','/research'],['Resilient Minds','/resilient-minds'],['Honours','/honours']];
function Link({to,children,className=''}){return <a className={className} href={to}>{children}</a>}
function Header(){const[open,setOpen]=useState(false);return <><header><Link to="/" className="brand"><img src="/assets/img/logo.svg"/><span>Women in Climate</span></Link><nav>{nav.map(n=><Link key={n[1]} to={n[1]}>{n[0]}</Link>)}</nav><div className="headright"><Link to="/funding" className="quiet">Funding</Link><Link to="/leadership" className="pill lime">Our organisation <ArrowUpRight size={15}/></Link></div><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>{open&&<div className="mobileNav">{[...nav,['Leadership','/leadership'],['Funding','/funding'],['WOMATEER','/womateer'],['The Vault','/merchandise']].map(n=><Link key={n[1]} to={n[1]}>{n[0]}<ChevronRight/></Link>)}</div>}</>}

const heroAssets={
home:{main:'/assets/img/team/pp.jpg',small:'/assets/img/news.png',label:'AFRICAN WOMEN · CLIMATE FUTURES',note:'From knowledge to visible leadership'},
she:{main:'/assets/img/she.png',small:'/assets/img/team/r.jpg',label:'SHE LEADS · 2026',note:'Learning becomes agency'},
wok:{main:'/assets/img/c.gif',small:'/assets/img/wok/19.svg',label:'LOCAL KNOWLEDGE · LIVING EVIDENCE',note:'Women already hold adaptation intelligence'},
circle:{main:'/assets/img/news.png',small:'/assets/img/testi/17.svg',label:'THE WOMATE CIRCLE',note:'Belonging can be climate infrastructure'},
research:{main:'/assets/img/team/pp.jpg',small:'/assets/img/oo.png',label:'EVIDENCE · DECISIONS · IMPACT',note:'Research built to move institutions'},
minds:{main:'/assets/img/team/asaa.jpeg',small:'/assets/img/oo1.png',label:'CLIMATE + WELLBEING',note:'Resilience includes the mind'},
honours:{main:'/assets/img/CH/NEW.png',small:'/assets/img/CH/c4444.png',label:'CLIMATE HONOURS · OCT 2026',note:'Visibility changes whose work becomes history'},
leadership:{main:'/assets/img/team/r.jpg',small:'/assets/img/team/asaa.jpeg',label:'WOMEN-LED · AFRICA-ROOTED',note:'Leadership across disciplines'},
funding:{main:'/assets/img/team/pp.jpg',small:'/assets/img/cert.svg',label:'FUNDING READINESS · 2026',note:'Strong work deserves a stronger application'},
volunteer:{main:'/assets/img/news.png',small:'/assets/img/team/r.jpg',label:'WOMATEER',note:'Professional talent for public value'},
merch:{main:'/assets/img/merch/13.png',small:'/assets/img/merch/14.png',label:'THE VAULT',note:'Wear the work'}
};
function HeroVisual({type}){let a=heroAssets[type]||heroAssets.home;return <div className={'heroVisual hv-'+type}>
  <div className="climateHalo"><span/><span/><span/></div>
  <div className="visualLabel"><i/> {a.label}</div>
  <div className="portraitFrame"><img src={a.main}/><div className="scanline"/></div>
  <div className="floatCard"><img src={a.small}/><span>{a.note}</span></div>
  <div className="dataPill"><Radio size={14}/><b>LIVE NETWORK</b><span>15 countries</span></div>
  <div className="africaStamp">AFRICA<br/><strong>→</strong><br/>FUTURE</div>
</div>}
function Hero({p}){return <section className={'hero hero-'+p.type}><div className="gridTexture"/><div className="heroTop"><div className="heroCopy"><div className="eyebrow">{p.k}</div><h1>{p.title}</h1><h2>{p.accent}</h2><p>{p.intro}</p><div className="actions"><a href="#content" className="pill lime">Explore the work <ArrowUpRight size={16}/></a><Link to="/circle" className="pill ghost">Join the community</Link></div><div className="heroSignal"><span>Women-led</span><span>Africa-rooted</span><span>Future-facing</span></div></div><HeroVisual type={p.type}/></div></section>}

const stats=[['40','graduates'],['15','countries'],['18+','honourees'],['1K+','lives reached']];
const programs=[
['She Leads','Climate learning to leadership.','/she-leads',<Sparkles/>,'/assets/img/team/r.jpg'],
['WoK—Action','Women’s knowledge as adaptation intelligence.','/wok-action',<Leaf/>,'/assets/img/wok/19.svg'],
['The Circle','A network built for belonging and opportunity.','/circle',<Users/>,'/assets/img/news.png'],
['Research','Evidence institutions can act on.','/research',<Microscope/>,'/assets/img/oo.png'],
['Resilient Minds','Mental health inside climate resilience.','/resilient-minds',<Brain/>,'/assets/img/team/asaa.jpeg'],
['Climate Honours','Visibility for women changing the field.','/honours',<Award/>,'/assets/img/CH/NEW.png']];
function Home(){return <><Hero p={pages['/']}/><main id="content">
<section className="statbar">{stats.map(s=><div key={s[1]}><strong>{s[0]}</strong><span>{s[1]}</span></div>)}</section>
<section className="manifesto"><div className="manifestoMark">W</div><div><div className="eyebrow dark">WHY WOMATE</div><h3>Climate leadership should look like the people already carrying communities through change.</h3></div><div><p className="lead">WOMATE works where climate, gender and local reality meet. We turn learning into agency, community knowledge into evidence, research into decisions and visibility into opportunity.</p><div className="pulseLine"><span/>One connected system—not isolated campaigns.</div></div></section>
<section className="programGrid">{programs.map((p,i)=><Link to={p[2]} className={'program p'+i} key={p[0]}><img className="programArt" src={p[4]}/><div className="programShade"/><div className="programTop"><div className="ico">{p[3]}</div><span>0{i+1}</span></div><div className="programCopy"><h4>{p[0]}</h4><p>{p[1]}</p><ArrowUpRight className="go"/></div></Link>)}</section>
<section className="impactScene"><div className="impactPhoto"><img src="/assets/img/c.gif"/><div className="mapGrid"/><button className="play"><Play fill="currentColor" size={16}/> Field story</button><div className="impactBadge"><Leaf/><span><b>WoK—Action</b>Living climate knowledge</span></div></div><div className="impactCopy"><div className="eyebrow dark">LOCAL KNOWLEDGE, LIVING EVIDENCE</div><h3>What women know about land, water and survival should not disappear between generations.</h3><p>WoK—Action creates a living archive of women’s climate knowledge while supporting communities to translate that intelligence into resilience, enterprise and local adaptation.</p><Link to="/wok-action" className="textlink">Enter WoK—Action <MoveRight/></Link></div></section>
<section className="facesRail"><div className="railIntro"><div className="eyebrow">THE WOMEN IN THE WORK</div><h3>Not beneficiaries.<br/>Climate actors.</h3><p>WOMATE is built around women as researchers, founders, community leaders, storytellers and decision-makers.</p></div><div className="faceCard f1"><img src="/assets/img/team/r.jpg"/><span>LEAD</span></div><div className="faceCard f2"><img src="/assets/img/team/asaa.jpeg"/><span>BUILD</span></div><div className="faceCard f3"><img src="/assets/img/team/pp.jpg"/><span>INFLUENCE</span></div><div className="characterCard"><img src="/assets/img/news.png"/><span>THE NEXT GENERATION</span></div></section>
<section className="voices"><div className="voicesHead"><div><div className="eyebrow dark">FROM THE NETWORK</div><h3>Leadership sounds different when women are given room to own it.</h3></div><div className="voiceOrb"><Globe2/><span>15<br/><small>countries</small></span></div></div><div className="quotes">{['I stopped seeing climate as a distant policy conversation. I could finally see where I belong in it.','The network gave me language for work I was already doing — and people who took that work seriously.','WOMATE connected learning to action. The confidence stayed long after the programme ended.'].map((q,i)=><article key={i}><Quote/><p>{q}</p><span>WOMATE alumna · Africa</span></article>)}</div></section>
<Honours/><Partner/></main></>}
function Honours(){return <section className="honours"><div className="honourCopy"><div className="eyebrow">CLIMATE HONOURS 2026</div><h3>Amplify the Untold.</h3><p>Nominate a woman whose climate leadership is changing a community, field or institution.</p><Link to="/honours" className="pill lime">Nominate a leader <ArrowUpRight/></Link><div className="honourCount">18+ <span>women already documented</span></div></div><div className="honourWall">{['NEW.png','c4444.png','c1.png','c10.png'].map((x,i)=><img key={x} src={'/assets/img/CH/'+x}/>)}</div></section>}
function Partner(){return <section className="partner"><div><div className="eyebrow dark">PARTNER WITH WOMATE</div><h3>Build climate action that women can lead, trust and sustain.</h3><div className="partnerLine"><Heart/> Research · Programmes · Community · Visibility</div></div><form onSubmit={e=>{e.preventDefault();alert('Thank you. Your enquiry has been captured for the WOMATE team.')}}><input required placeholder="Name"/><input required type="email" placeholder="Work email"/><select><option>Partnership enquiry</option><option>Research</option><option>Programme collaboration</option><option>Funding</option></select><textarea placeholder="What would you like to build together?"/><button className="pill darkbtn">Send enquiry <ArrowUpRight/></button></form></section>}

const details={
she:{items:['Climate foundations','Gender and climate justice','Governance and policy','Advocacy and storytelling','Leadership and community engagement','Climate careers'],title:'Six pillars. One leadership trajectory.',aside:'2026 cohort registration'},
wok:{items:['Indigenous sovereignty','Impact visibility','Economic empowerment','Collective inquiry','Community wealth','Living archives'],title:'Community knowledge, protected and put to work.',aside:'Community-project funding'},
circle:{items:['Membership activation','Member pathways','Community access','Climate Honours access','Peer opportunities','Professional visibility'],title:'A network designed to compound women’s climate agency.',aside:'Registration & payment'},
research:{items:['Climate & gender intelligence','MEL and impact analysis','Evidence support','Community co-creation','Programme design','Knowledge management','Wellbeing & protection','Institutional capacity'],title:'Research made useful, legible and actionable.',aside:'Commission research'},
minds:{items:['Rescue','Restore','Resilience','Peer support pathways','Climate wellbeing research','Guardianship contribution'],title:'The human nervous system belongs in climate strategy.',aside:'Support the programme'},
honours:{items:['The Spotlight','The Circle','The Honour','2025 archive — 18 women','2026 nominations','Journey to October 2026'],title:'Recognition that creates memory, credibility and connection.',aside:'Submit a nomination'},
funding:{items:['Professional application review','Application streamlining','Grant-writing webinar','Technical capacity building','WOMATE community access','Competitive positioning'],title:'From strong idea to stronger application.',aside:'GHS 200 registration'},
volunteer:{items:['Visual Strategist','Digital Systems Lead','Impact Storyteller','Community Impact Lead','Research support','Programme operations'],title:'Bring your professional edge to climate work that matters.',aside:'Apply to volunteer'},
merch:{items:['Signature WOMATE T-shirt','Climate action edition','Circle member edition','Limited programme drops'],title:'The Vault',aside:'Shop WOMATE'},
leadership:{items:['Phillipa Aidoo','Asaa Gyebi-Adjei','Ruby Damenshie-Brown','Hamza Abubakar'],title:'Leadership across climate, technology, research and community.',aside:'Partnership invitation'}};
const pageGallery={she:['/assets/img/team/r.jpg','/assets/img/she.png','/assets/img/cert.svg'],wok:['/assets/img/c.gif','/assets/img/wok/17.svg','/assets/img/wok/20.svg'],circle:['/assets/img/news.png','/assets/img/testi/19.svg','/assets/img/testi/20.svg'],research:['/assets/img/team/pp.jpg','/assets/img/oo.png','/assets/img/featured-img.svg'],minds:['/assets/img/team/asaa.jpeg','/assets/img/news.png','/assets/img/oo1.png'],honours:['/assets/img/CH/NEW.png','/assets/img/CH/c4444.png','/assets/img/CH/c1.png'],leadership:['/assets/img/team/r.jpg','/assets/img/team/asaa.jpeg','/assets/img/team/h.jpg'],funding:['/assets/img/team/pp.jpg','/assets/img/cert.svg','/assets/img/news.png'],volunteer:['/assets/img/news.png','/assets/img/team/r.jpg','/assets/img/team/asaa.jpeg'],merch:['/assets/img/merch/13.png','/assets/img/merch/14.png','/assets/img/merch/12.png']};
function Standard({p}){const d=details[p.type],g=pageGallery[p.type]||pageGallery.she;return <><Hero p={p}/><main id="content"><section className="programmeIntro"><div><div className="eyebrow dark">THE WORK</div><h3>{d.title}</h3></div><div><p className="lead">Built for credibility in the room and usefulness on the ground. WOMATE combines rigorous thinking with accessible delivery so women can move from participation to influence.</p><div className="miniProof"><ShieldCheck/> Africa-rooted · evidence-led · community-built</div></div></section><section className="galleryTriptych"><figure className="gBig"><img src={g[0]}/><figcaption>WOMATE · {p.k}</figcaption></figure><figure><img src={g[1]}/></figure><figure><img src={g[2]}/></figure></section><section className="featureList">{d.items.map((x,i)=><div className="feature" key={x}><span>0{i+1}</span><h4>{x}</h4><ArrowUpRight/></div>)}</section>{p.type==='she'&&<section className="certificateScene"><div><div className="eyebrow">CERTIFICATE PATHWAY</div><h3>Learning should leave women with proof, practice and a stronger next step.</h3><p>Structured learning, applied reflection and visible evidence of completion.</p></div><img src="/assets/img/cert.svg"/></section>}{p.type==='leadership'&&<LeadershipFaces/>}{p.type==='honours'&&<Honours/>}{p.type==='merch'&&<Store/>}<section className="ctaBand"><div><div className="eyebrow">NEXT STEP</div><h3>{d.aside}</h3></div><Link to="/circle" className="pill lime">Start here <ArrowUpRight/></Link></section>{['funding','volunteer','honours','circle'].includes(p.type)&&<Application type={p.type}/>}<Partner/></main></>}
function LeadershipFaces(){return <section className="leadershipFaces">{[['r.jpg','Phillipa Aidoo'],['asaa.jpeg','Asaa Gyebi-Adjei'],['a.png','Ruby Damenshie-Brown'],['h.jpg','Hamza Abubakar']].map(([im,n])=><article key={n}><img src={'/assets/img/team/'+im}/><div><span>WOMATE LEADERSHIP</span><h4>{n}</h4></div></article>)}</section>}
function Store(){return <section className="store"><div className="productStage"><img src="/assets/img/merch/13.png"/><span>LIMITED EDITION</span></div><div><div className="eyebrow dark">THE VAULT</div><h3>WOMATE Signature Tee</h3><p>Designed as a clean symbol of women-led climate action. Limited availability.</p><div className="merchMini"><img src="/assets/img/merch/12.png"/><img src="/assets/img/merch/14.png"/></div><button className="pill darkbtn">Purchase enquiry <ArrowUpRight/></button></div></section>}
function Application({type}){return <section className="application"><div><div className="eyebrow dark">APPLICATION</div><h3>{type==='honours'?'Tell us whose work deserves to be seen.':'Your next step starts here.'}</h3><p>Complete the short form. WOMATE will review your submission and follow up through the contact details you provide.</p></div><form onSubmit={e=>{e.preventDefault();alert('Submission received.')}}><input required placeholder="Full name"/><input required type="email" placeholder="Email address"/><input placeholder="Country"/><textarea placeholder="Tell us briefly about your interest"/><button className="pill darkbtn">Submit <ArrowUpRight/></button></form></section>}
function Footer(){return <footer><div className="footbrand"><img src="/assets/img/logo.svg"/><h3>African women leading climate action.</h3><div className="footOrb"><Leaf/><span>Knowledge<br/>Technology<br/>Community</span></div></div><div className="footlinks"><div><b>Programmes</b>{nav.slice(0,4).map(n=><Link key={n[1]} to={n[1]}>{n[0]}</Link>)}</div><div><b>Organisation</b><Link to="/leadership">Leadership</Link><Link to="/funding">Funding support</Link><Link to="/womateer">WOMATEER</Link><Link to="/merchandise">The Vault</Link></div><div><b>Connect</b><a href="mailto:hello@womate.org">hello@womate.org</a><span>Africa · Global network</span></div></div><div className="bottom"><span>© 2026 WOMATE. Women in Climate.</span><span>Women-led · Africa-rooted · Future-facing</span></div></footer>}
function App(){let path=window.location.pathname.replace(/\/$/,'')||'/';let p=pages[path]||pages['/'];useEffect(()=>window.scrollTo(0,0),[]);return <><Header/>{p.type==='home'?<Home/>:<Standard p={p}/>}<Footer/></>}
createRoot(document.getElementById('root')).render(<App/>);
