const fs=require('fs'),path=require('path');
const root=process.cwd();
const pkg=__dirname;
const currentMain=path.join(root,'src','main.jsx');
const updatedMain=path.join(pkg,'src','main.jsx');
const style=path.join(root,'src','style.css');
const cssFile=path.join(pkg,'LEGAL_PAGES.css');
if(!fs.existsSync(currentMain)||!fs.existsSync(style))throw new Error('Run this from the WOMATE project root.');
const current=fs.readFileSync(currentMain,'utf8');
if(!current.includes("function Footer(){return"))throw new Error('Current src/main.jsx does not match the WOMATE source expected by this patch.');
if(!current.includes("Africa · connected globally"))throw new Error('Current source does not appear to be the validated 12 Sep WOMATE build. Patch stopped safely.');
fs.copyFileSync(updatedMain,currentMain);
let css=fs.readFileSync(style,'utf8');
const marker='/* WOMATE legal pages · Privacy Policy + Terms of Service */';
if(!css.includes(marker))css+='\n\n'+fs.readFileSync(cssFile,'utf8')+'\n';
fs.writeFileSync(style,css,'utf8');
console.log('WOMATE Privacy Policy + Terms of Service installed.');
console.log('Routes: /privacy and /terms');
console.log('Global footer links added.');
console.log('NEXT: npm run build');
