import './selectedBrandEnhancements.css';

const TAGS='#WOMATE #SheLeads #SheLeads2026 #WomenInClimate #ClimateLeadership #WomenLeadingClimateAction #AfricanWomenInClimate #ClimateAction #InclusiveClimateAction';
function valByLabel(label){const els=[...document.querySelectorAll('input')]; const x=els.find(el=>{const p=el.closest('label,div');return p&&p.textContent.toLowerCase().includes(label.toLowerCase())});return x?.value?.trim()||''}
function learnerName(){return valByLabel('full name')||valByLabel('name')||''}
function caption(){const n=learnerName();return `${n?`${n} — `:""}I’m excited to share that I have been selected for the She Leads Climate Mentorship Programme — Cohort 2 by WOMATE.\n\nOver the coming weeks, I’ll be strengthening my climate knowledge, leadership and capacity to turn learning into meaningful action.\n\nI’m looking forward to learning, connecting and contributing alongside an incredible community of emerging women climate leaders across Africa.\n\nDriving inclusive climate action with technology.`;}
function copy(t,b){navigator.clipboard?.writeText(t).then(()=>{const old=b.textContent;b.textContent='Copied';setTimeout(()=>b.textContent=old,1600)});}
function mount(){if(document.querySelector('.selected-share-kit'))return; const host=document.querySelector('main')||document.body; const box=document.createElement('section');box.className='selected-share-kit';box.innerHTML=`<div class="selected-share-eyebrow">READY TO SHARE</div><h2>Suggested caption</h2><p class="selected-share-note">Make it yours before you post.</p><div class="selected-caption-text"></div><div class="selected-share-actions"><button type="button" class="selected-copy-caption">Copy caption</button></div><h3>Suggested hashtags</h3><div class="selected-hashtags"></div><div class="selected-share-actions"><button type="button" class="selected-copy-tags">Copy hashtags</button></div></section>`;host.appendChild(box);const ct=box.querySelector('.selected-caption-text'),ht=box.querySelector('.selected-hashtags');ct.textContent=caption();ht.textContent=TAGS;box.querySelector('.selected-copy-caption').onclick=e=>copy(caption(),e.currentTarget);box.querySelector('.selected-copy-tags').onclick=e=>copy(TAGS,e.currentTarget);document.addEventListener('input',()=>ct.textContent=caption());}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,250));else setTimeout(mount,250);
