import React,{useEffect,useMemo,useState}from'react';
import{ArrowRight,BarChart3,Check,ClipboardCheck,Copy,FileText,KeyRound,LockKeyhole,RefreshCw,ShieldCheck,Sparkles,Star,UsersRound,XCircle}from'lucide-react';
import{activateTeamAccess,createTeamAccessCode,generateStandardTeamPack,getStaffDashboardPreview,listTeamAccess,nominateCanopySpotlight,revokeTeamAccessCode,setStaffMembershipStatus,updateCanopySpotlightStatus}from'./canopyTeamAccessApi';

export const TEAM_ROLES={
 programme_manager:'Programme & Monitoring Manager',
 programme_operations:'Programme Operations Deputy',
 module_coordinator:'Learning Experience Coordinator',
 learning_fellow:'Learning Experience Fellow'
};
export const MODULES=[
 ['module-01','01 · Understanding Climate Change'],
 ['module-02','02 · Gender & Climate Justice'],
 ['module-03','03 · Climate Governance & Policy'],
 ['module-04','04 · Climate Advocacy & Digital Innovation'],
 ['module-05','05 · Leadership & Professional Pathways']
];
export const teamRoleLabel=role=>TEAM_ROLES[role]||String(role||'').replaceAll('_',' ');
export const isTeamRole=role=>Boolean(TEAM_ROLES[role]);
const moduleLabel=id=>MODULES.find(([value])=>value===id)?.[1]||'All modules';
const expiryDefault=()=>{const d=new Date(Date.now()+14*86400000);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
const copyText=async text=>{try{await navigator.clipboard.writeText(text)}catch{const el=document.createElement('textarea');el.value=text;document.body.appendChild(el);el.select();document.execCommand('copy');el.remove()}};

export function CanopyTeamActivation({viewer,onActivated}){
 const[code,setCode]=useState('');const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[success,setSuccess]=useState(false);
 const activate=async e=>{e.preventDefault();setBusy(true);setMsg('');try{const access=await activateTeamAccess(viewer?.session,code);setSuccess(true);setMsg(`${teamRoleLabel(access?.role)} access activated${access?.module_id?` for ${moduleLabel(access.module_id)}`:''}.`);setCode('');setTimeout(()=>onActivated?.(),600)}catch(err){setMsg(err.message||'Unable to activate team access.')}finally{setBusy(false)}};
 return <main className="canopyTeamActivate"><section><div className="canopyTeamActivateIcon"><KeyRound/></div><span className="canopyEyebrow">WOMATE TEAM ACCESS</span><h1>Activate your programme role.</h1><p>Your code is single-use. Once activated, your role is permanently connected to this Canopy account and future sign-ins use only your email and password.</p><form onSubmit={activate}><label>Team Access Code<input required autoCapitalize="characters" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="SL2-XXXXXX-XXXXXX-XXXXXX-XXXXXX"/></label><button className="canopyPrimary" disabled={busy}>{busy?'Activating…':'Activate team access'} <ArrowRight size={16}/></button></form>{msg&&<p className={`canopyFormMsg ${success?'success':'error'}`}>{msg}</p>}<div className="canopyTeamActivateNote"><ShieldCheck/><span>Codes are role-bound, single-use, expiring and auditable. They do not replace your password.</span></div></section></main>
}

export function CanopyAdminRolePreview({viewer}){
 const params=new URLSearchParams(window.location.search);
 const initialRole=TEAM_ROLES[params.get('role')]?params.get('role'):'programme_manager';
 const initialModule=params.get('module')||'module-01';
 const[role,setRole]=useState(initialRole);const[moduleId,setModuleId]=useState(initialModule);const[data,setData]=useState(null);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');
 const needsModule=['module_coordinator','learning_fellow'].includes(role);
 const load=async(nextRole=role,nextModule=moduleId)=>{setBusy(true);setMsg('');try{setData(await getStaffDashboardPreview(viewer.session,{role:nextRole,moduleId:['module_coordinator','learning_fellow'].includes(nextRole)?nextModule:null}))}catch(e){setMsg(e.message||'Unable to open this dashboard preview.')}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const changeRole=e=>{const next=e.target.value;setRole(next);const url=`/canopy/manage/role-preview?role=${encodeURIComponent(next)}${['module_coordinator','learning_fellow'].includes(next)?`&module=${encodeURIComponent(moduleId)}`:''}`;window.history.replaceState({},'',url);load(next,moduleId)};
 const changeModule=e=>{const next=e.target.value;setModuleId(next);window.history.replaceState({},'',`/canopy/manage/role-preview?role=${encodeURIComponent(role)}&module=${encodeURIComponent(next)}`);load(role,next)};
 return <main className="canopyManager canopyAdminRolePreview"><section className="canopyPreviewGuard"><div><ShieldCheck/><span>ADMIN PREVIEW MODE</span></div><h1>Test a delivery-team dashboard.</h1><p>You remain signed in as WOMATE Admin. No Team Access Code is consumed and no staff identity is impersonated.</p><div className="canopyPreviewControls"><label>Dashboard<select value={role} onChange={changeRole}>{Object.entries(TEAM_ROLES).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>{needsModule&&<label>Module<select value={moduleId} onChange={changeModule}>{MODULES.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>}<button className="canopySecondary" type="button" onClick={()=>{window.history.pushState({},'','/canopy/manage/team-access');window.dispatchEvent(new PopStateEvent('popstate'))}}>Return to Team Access</button></div>{msg&&<p className="canopyFormMsg error">{msg}</p>}</section>{busy?<section className="canopyPreviewLoading"><RefreshCw/> Loading dashboard preview…</section>:data?<CanopyStaffDashboard viewer={viewer} access={{role,module_id:needsModule?moduleId:null,status:'preview'}} data={data} onReload={()=>load()}/>:null}</main>
}

export function CanopyTeamAccessAdmin({viewer}){
 const[data,setData]=useState({codes:[],members:[]});const[busy,setBusy]=useState('');const[msg,setMsg]=useState('');const[issued,setIssued]=useState([]);
 const[form,setForm]=useState({role:'programme_manager',moduleId:'',expiresAt:expiryDefault()});
 const needsModule=['module_coordinator','learning_fellow'].includes(form.role);
 const load=async()=>{setBusy('load');try{setData(await listTeamAccess(viewer.session));setMsg('')}catch(e){setMsg(e.message)}finally{setBusy('')}};
 useEffect(()=>{load()},[viewer?.session?.access_token]);
 const create=async e=>{e.preventDefault();if(needsModule&&!form.moduleId){setMsg('Select the module for this role.');return}setBusy('create');setMsg('');try{const rows=await createTeamAccessCode(viewer.session,{role:form.role,moduleId:needsModule?form.moduleId:null,expiresAt:form.expiresAt?new Date(form.expiresAt).toISOString():null});setIssued(Array.isArray(rows)?rows:[rows]);setMsg('Access code created. Copy it now; Canopy stores only its secure hash.');await load()}catch(err){setMsg(err.message)}finally{setBusy('')}};
 const pack=async()=>{setBusy('pack');setMsg('');try{const rows=await generateStandardTeamPack(viewer.session,{expiresAt:form.expiresAt?new Date(form.expiresAt).toISOString():null});setIssued(Array.isArray(rows)?rows:[rows]);setMsg('Cohort 2 team pack generated: 1 Programme Manager, 1 Deputy, 5 Coordinators and 15 Fellows.');await load()}catch(err){setMsg(err.message)}finally{setBusy('')}};
 const revoke=async id=>{if(!window.confirm('Revoke this unused Team Access Code?'))return;setBusy(id);try{await revokeTeamAccessCode(viewer.session,id);await load()}catch(e){setMsg(e.message)}finally{setBusy('')}};
 const membership=async(member,status)=>{if(!window.confirm(`${status==='inactive'?'Deactivate':'Reactivate'} ${member.full_name||member.email||'this team member'}?`))return;setBusy(member.user_id);try{await setStaffMembershipStatus(viewer.session,member.user_id,status);await load()}catch(e){setMsg(e.message)}finally{setBusy('')}};
 const issuedText=issued.map(r=>`${teamRoleLabel(r.role)}${r.module_id?` · ${moduleLabel(r.module_id)}`:''}\n${r.access_code}\nExpires ${new Date(r.expires_at).toLocaleString()}`).join('\n\n');
 return <main className="canopyManager canopyTeamAdmin"><div className="canopyPageHead"><span className="canopyEyebrow">WOMATE · CONTROLLED ACCESS</span><h1>Team Access</h1><p>Create role-bound access before team selection. Each selected person activates one code with their own email and password.</p></div>{msg&&<p className="canopyFormMsg" role="status">{msg}</p>}
 <section className="canopyAdminPreviewPanel"><div><span>ADMIN TESTING</span><h2>Preview every staff dashboard without using a code.</h2><p>Single-use codes stay reserved for the selected team member. Admin Preview lets WOMATE test Manager, Deputy, Coordinator and Fellow experiences at any time.</p></div><div className="canopyAdminPreviewActions"><button className="canopySecondary" type="button" onClick={()=>{window.history.pushState({},'','/canopy/manage/role-preview?role=programme_manager');window.dispatchEvent(new PopStateEvent('popstate'))}}>Programme Manager</button><button className="canopySecondary" type="button" onClick={()=>{window.history.pushState({},'','/canopy/manage/role-preview?role=programme_operations');window.dispatchEvent(new PopStateEvent('popstate'))}}>Operations Deputy</button><button className="canopySecondary" type="button" onClick={()=>{window.history.pushState({},'','/canopy/manage/role-preview?role=module_coordinator&module=module-01');window.dispatchEvent(new PopStateEvent('popstate'))}}>Coordinator</button><button className="canopySecondary" type="button" onClick={()=>{window.history.pushState({},'','/canopy/manage/role-preview?role=learning_fellow&module=module-01');window.dispatchEvent(new PopStateEvent('popstate'))}}>Learning Fellow</button></div></section>
 <section className="canopyTeamAccessGrid"><form className="canopyOpsForm" onSubmit={create}><div className="canopySectionHead"><span>ONE PERSON</span><h2>Create access code</h2><p>No email is required now. The code binds to the first authenticated person who successfully activates it.</p></div><div className="canopyOpsFormGrid"><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value,moduleId:''})}>{Object.entries(TEAM_ROLES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{needsModule&&<label>Assigned module<select required value={form.moduleId} onChange={e=>setForm({...form,moduleId:e.target.value})}><option value="">Select module</option>{MODULES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}<label>Code expires<input type="datetime-local" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})}/></label></div><button className="canopyPrimary" disabled={busy==='create'}>{busy==='create'?'Creating…':'Create single-use code'} <KeyRound size={16}/></button></form>
 <section className="canopyTeamPack"><div><span>COHORT 2 STRUCTURE</span><h2>Generate the complete delivery team.</h2><p>One action creates <b>22 separate codes</b>: 1 Programme Manager, 1 Programme Operations Deputy, 5 Learning Experience Coordinators and 15 Learning Experience Fellows — three Fellows assigned to each module.</p></div><div className="canopyTeamPackNumbers"><strong>1</strong><span>Manager</span><strong>1</strong><span>Deputy</span><strong>5</strong><span>Coordinators</span><strong>15</strong><span>Fellows</span></div><button className="canopySecondary" type="button" disabled={busy==='pack'} onClick={pack}>{busy==='pack'?'Generating…':'Generate Cohort 2 team pack'} <UsersRound size={16}/></button></section></section>
 {issued.length>0&&<section className="canopyIssuedCodes"><header><div><span>NEW CODES · COPY NOW</span><h2>{issued.length} access code{issued.length===1?'':'s'} created</h2></div><button className="canopySecondary" onClick={()=>copyText(issuedText)}><Copy size={15}/> Copy all</button></header><div>{issued.map((r,i)=><article key={`${r.access_code}-${i}`}><div><b>{teamRoleLabel(r.role)}</b><small>{r.module_id?moduleLabel(r.module_id):'All programme operations'} · expires {new Date(r.expires_at).toLocaleDateString()}</small></div><code>{r.access_code}</code><button title="Copy code" onClick={()=>copyText(r.access_code)}><Copy size={15}/></button></article>)}</div><p>For security, full codes are shown only in this result. The database keeps a hash, not the reusable plaintext code.</p></section>}
 <section className="canopyTeamAdminSection"><header><div><span>ACTIVE TEAM</span><h2>{data.members?.length||0} activated accounts</h2></div><button className="canopyTextBtn" onClick={load} disabled={busy==='load'}><RefreshCw size={15}/> Refresh</button></header><div className="canopyTeamMemberList">{data.members?.length?data.members.map(m=><article key={m.user_id}><div className="canopyTeamMemberAvatar">{String(m.full_name||m.email||'?').trim().charAt(0).toUpperCase()}</div><div><b>{m.full_name||'Team member'}</b><span>{m.email||'—'}</span><small>{teamRoleLabel(m.role)}{m.module_id?` · ${moduleLabel(m.module_id)}`:''}</small></div><span className={`canopyAccessStatus ${m.status==='active'?'isActive':'isWaiting'}`}>{m.status}</span><button className="canopySecondary" disabled={busy===m.user_id} onClick={()=>membership(m,m.status==='active'?'inactive':'active')}>{m.status==='active'?'Deactivate':'Reactivate'}</button></article>):<p>No team member has activated a code yet.</p>}</div></section>
 <section className="canopyTeamAdminSection"><header><div><span>CODE REGISTER</span><h2>{data.codes?.length||0} generated codes</h2></div></header><div className="canopyCodeRegister">{data.codes?.length?data.codes.map(c=><article key={c.id}><div><b>{teamRoleLabel(c.role)}</b><small>{c.module_id?moduleLabel(c.module_id):'All programme operations'}</small></div><code>{c.code_hint}</code><span>{c.status}</span><span>{new Date(c.expires_at).toLocaleDateString()}</span>{c.status==='active'?<button title="Revoke" onClick={()=>revoke(c.id)} disabled={busy===c.id}><XCircle size={17}/></button>:<Check size={17}/>}</article>):<p>No codes generated yet.</p>}</div></section>
 </main>
}

const CATEGORY_OPTIONS=[['strongest_insight','Strongest insight'],['canopycanvas','Strongest CanopyCanvas'],['local_application','Best local climate application'],['emerging_leadership','Emerging leadership'],['policy_idea','Thoughtful policy idea']];
export function CanopyStaffDashboard({viewer,access,data,onReload}){
 const role=access?.role;const moduleId=access?.module_id;const counts=data?.counts||{};const rows=data?.recent_submissions||[];const spotlights=data?.spotlights||[];
 const[busy,setBusy]=useState('');const[msg,setMsg]=useState('');const[nomination,setNomination]=useState({submissionId:'',category:'strongest_insight',note:''});
 const title=role==='programme_manager'?'Programme & Monitoring':role==='programme_operations'?'Programme Operations':role==='module_coordinator'?'Learning Experience Coordination':'Learning Experience';
 const mission=role==='programme_manager'?'Lead programme quality, monitoring, assessment decisions and the team responsible for the learner experience.':role==='programme_operations'?'Keep every part of She Leads delivery ready, on time and connected.':role==='module_coordinator'?`Produce an exceptional ${moduleLabel(moduleId)} learning experience.`:'Make sure learners do not disappear into an online course.';
 const nominate=async e=>{e.preventDefault();setBusy('nominate');setMsg('');try{await nominateCanopySpotlight(viewer.session,{submissionId:nomination.submissionId,category:nomination.category,note:nomination.note});setMsg('Canopy Spotlight nomination saved.');setNomination({submissionId:'',category:'strongest_insight',note:''});await onReload?.()}catch(err){setMsg(err.message)}finally{setBusy('')}};
 const decide=async(id,status)=>{setBusy(id);setMsg('');try{await updateCanopySpotlightStatus(viewer.session,{nominationId:id,status});setMsg('Spotlight status updated.');await onReload?.()}catch(err){setMsg(err.message)}finally{setBusy('')}};
 return <main className="canopyManager canopyStaffDashboard"><div className="canopyPageHead"><span className="canopyEyebrow">SHE LEADS · COHORT 2</span><h1>{title}</h1><p>{mission}</p>{moduleId&&<b className="canopyStaffModule">{moduleLabel(moduleId)}</b>}</div>{msg&&<p className="canopyFormMsg">{msg}</p>}
 <section className="canopyManagerStats canopyStaffStats"><article><strong>{counts.learners??0}</strong><span>learners</span></article><article><strong>{counts.active_access??0}</strong><span>active access</span></article><article><strong>{counts.submissions??0}</strong><span>{moduleId?'module submissions':'submissions'}</span></article><article><strong>{counts.needs_attention??0}</strong><span>need attention</span></article></section>
 {role==='programme_operations'&&<section className="canopyOpsGrid"><article className="canopyStaffMandate"><ClipboardCheck/><span><b>Readiness</b><small>Keep deadlines, live-session preparation and operational actions moving.</small></span></article><article className="canopyStaffMandate"><BarChart3/><span><b>Programme pulse</b><small>Surface exceptions and concise operational signals for the Programme Manager.</small></span></article><article className="canopyStaffMandate"><UsersRound/><span><b>Team follow-through</b><small>Follow up with coordinators before issues become programme-level escalations.</small></span></article><article className="canopyStaffMandate"><ShieldCheck/><span><b>Escalation boundary</b><small>Operational execution belongs here; final assessment and sensitive programme decisions stay with the Programme Manager/WOMATE.</small></span></article></section>}
 <section className="canopyTeamAdminSection"><header><div><span>LEARNING PULSE</span><h2>{moduleId?'Recent work in your module':'Recent learner submissions'}</h2><p>{role==='learning_fellow'?'Use this queue to notice strong work, recurring learning needs and learners worth surfacing — not to become a manual attendance clerk.':'Use this view to identify patterns, exceptions and strong learner work.'}</p></div></header><div className="canopyStaffSubmissionList">{rows.length?rows.map(s=><article key={s.id}><header><div><small>{s.module_label||s.week_key} · Attempt {s.attempt_no}</small><h3>{s.learner_name||'Learner'}</h3><span>{s.country||'—'} · {new Date(s.submitted_at).toLocaleString()}</span></div><div><strong>{s.score!=null?`${s.score}/100`:'—'}</strong><small>{s.score_band||s.assessment_status||'Awaiting assessment'}</small></div></header>{s.paragraph_excerpt&&<p>{s.paragraph_excerpt}{s.paragraph_excerpt.length>=315?'…':''}</p>}<footer>{s.canvas_link&&<a href={s.canvas_link} target="_blank" rel="noreferrer">Open CanopyCanvas <ArrowRight size={14}/></a>}<button className="canopySecondary" onClick={()=>setNomination({...nomination,submissionId:s.id})}><Star size={14}/> Nominate for Spotlight</button></footer></article>):<p>No submissions are available in this scope yet.</p>}</div></section>
 {nomination.submissionId&&<form className="canopyOpsForm canopySpotlightForm" onSubmit={nominate}><div className="canopySectionHead"><span>CANOPY SPOTLIGHT</span><h2>Nominate exceptional learner work</h2><p>Spotlight is for work worth seeing — not simply the highest score.</p></div><div className="canopyOpsFormGrid"><label>Category<select value={nomination.category} onChange={e=>setNomination({...nomination,category:e.target.value})}>{CATEGORY_OPTIONS.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="wide">Why this work matters<textarea rows="3" maxLength="600" value={nomination.note} onChange={e=>setNomination({...nomination,note:e.target.value})} placeholder="What should the programme team notice?"/></label></div><div className="canopySpotlightActions"><button type="button" className="canopySecondary" onClick={()=>setNomination({submissionId:'',category:'strongest_insight',note:''})}>Cancel</button><button className="canopyPrimary" disabled={busy==='nominate'}>{busy==='nominate'?'Saving…':'Save nomination'} <Sparkles size={15}/></button></div></form>}
 <section className="canopyTeamAdminSection"><header><div><span>CANOPY SPOTLIGHT</span><h2>{spotlights.length} nomination{spotlights.length===1?'':'s'}</h2></div></header><div className="canopySpotlightList">{spotlights.length?spotlights.map(n=><article key={n.id}><Star/><div><b>{CATEGORY_OPTIONS.find(([v])=>v===n.category)?.[1]||n.category}</b><span>{n.learner_name||'Learner'} · {moduleLabel(n.module_id)}</span>{n.note&&<p>{n.note}</p>}</div><span className={`canopyAccessStatus ${n.status==='featured'?'isActive':'isWaiting'}`}>{n.status}</span>{['programme_manager','programme_operations'].includes(role)&&<div className="canopySpotlightDecision">{role==='programme_operations'&&n.status==='nominated'&&<button onClick={()=>decide(n.id,'shortlisted')} disabled={busy===n.id}>Shortlist</button>}{role==='programme_manager'&&<><button onClick={()=>decide(n.id,'featured')} disabled={busy===n.id}>Feature</button><button onClick={()=>decide(n.id,'declined')} disabled={busy===n.id}>Decline</button></>}</div>}</article>):<p>No Spotlight nominations yet.</p>}</div></section>
 </main>
}
