export const CLIMATE_DEBATE_MOTIONS=[
{id:1,motion:'Africa should prioritise climate adaptation over climate mitigation.',forCase:'Africa contributes relatively little to historical emissions but faces significant climate impacts. Limited resources should prioritise protecting communities from impacts already happening.',againstCase:'Prioritising adaptation alone does not address the systems driving climate change, and Africa’s future development needs low-carbon pathways.'},
{id:2,motion:'Social media activism creates more awareness than meaningful climate action.',forCase:'Digital campaigns can become performative, reward outrage and engagement metrics, and rarely translate into structural change.',againstCase:'Social media can mobilise communities, influence public conversations, pressure institutions, raise funds, spread information and connect people to offline action.'},
{id:3,motion:'Individual lifestyle changes are less important than holding governments and corporations accountable.',forCase:'Individual actions cannot substitute for systemic change, especially when infrastructure and policy constrain people’s choices.',againstCase:'Collective individual behaviour creates demand, shifts culture and can influence markets and political priorities.'},
{id:4,motion:'Artificial intelligence will accelerate climate solutions more than it will worsen the climate crisis.',forCase:'AI can support climate modelling, early-warning systems, agriculture, energy optimisation, disaster response, research and resource management.',againstCase:'AI requires substantial energy and infrastructure, can increase demand for computing resources, and its benefits may not be equally distributed.'},
{id:5,motion:'Climate communication should prioritise hope over fear.',forCase:'Constant crisis messaging can create climate anxiety, fatigue and helplessness. Hope can help people see that action is possible.',againstCase:'Overly positive messaging can minimise the seriousness and urgency of the crisis. Sometimes people need uncomfortable truths before they act.'}
];
function stableNumber(value){const text=String(value||'womate-climate-debate');let hash=2166136261;for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619)}return hash>>>0}
export function climateDebateAssignment(userId){const index=stableNumber(userId)%10;const motion=CLIMATE_DEBATE_MOTIONS[Math.floor(index/2)];const position=index%2===0?'FOR':'AGAINST';return{motion,position,caseText:position==='FOR'?motion.forCase:motion.againstCase}}
export function isClimateDebateSocialUrl(value){try{const url=new URL(String(value||'').trim());if(!['http:','https:'].includes(url.protocol))return false;const host=url.hostname.toLowerCase().replace(/^www\./,'');return['linkedin.com','lnkd.in','x.com','twitter.com','t.co','instagram.com','facebook.com','fb.com','threads.net','tiktok.com','youtube.com','youtu.be','bsky.app'].some(domain=>host===domain||host.endsWith('.'+domain))}catch{return false}}
