import React,{useEffect,useMemo,useState}from'react';
import{BadgeCheck,BriefcaseBusiness,Globe2,Handshake,Search,ShieldCheck,Sparkles,UsersRound}from'lucide-react';
import{getCanopyTalentNetwork,saveCanopyTalentSettings,sendCanopyCollaborationRequest,respondCanopyCollaborationRequest,getAdminCanopyTalentNetwork,setAdminCanopyTalentVisibility}from'./canopyApi';
import'./canopyTalentNetwork.css';

const clean=v=>String(v||'').trim();
const interestList=v=>Array.isArray(v)?v:[];

export default function CanopyTalentNetwork({viewer}){
 const[data,setData]=useState({directory:[],incoming:[],outgoing:[],me:{}}),[query,setQuery]=useState(''),[country,setCountry]=useState('all'),[mentorOnly,setMentorOnly]=useState(false),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[note,setNote]=useState({});
 const load=async()=>{try{setData(await getCanopyTalentNetwork(viewer.session)||{directory:[],incoming:[],outgoing:[],me:{}});setMsg('')}catch(e){setMsg(e.message)}};
 useEffect(()=>{load()},[]);
 const me=data.me||{};
 const countries=useMemo(()=>Array.from(new Set((data.directory||[]).map(x=>x.country).filter(Boolean))).sort(),[data.directory]);
 const rows=useMemo(()=>{const q=query.trim().toLowerCase();return(data.directory||[]).filter(x=>(country==='all'||x.country===country)&&(!mentorOnly||x.mentor_available)&&(!q||[x.full_name,x.country,x.headline,...interestList(x.climate_interests)].some(v=>String(v||'').toLowerCase().includes(q))))},[data.directory,query,country,mentorOnly]);
 const save=async patch=>{setBusy('settings');try{await saveCanopyTalentSettings(viewer.session,{discoverable:patch.discoverable??me.discoverable,mentorAvailable:patch.mentor_available??me.mentor_available,collaborationOpen:patch.collaboration_open??me.collaboration_open,headline:patch.headline??me.headline,interests:patch.climate_interests??interestList(me.climate_interests)});await load();setMsg('Talent profile updated.')}catch(e){setMsg(e.message)}finally{setBusy('')}};
 const send=async userId=>{const text=clean(note[userId]);if(!text){setMsg('Add a short collaboration note first.');return}setBusy(userId);try{await sendCanopyCollaborationRequest(viewer.session,userId,text);setNote(n=>({...n,[userId]:''}));await load();setMsg('Collaboration request sent.')}catch(e){setMsg(e.message)}finally{setBusy('')}};
 const respond=async(id,accept)=>{setBusy(id);try{await respondCanopyCollaborationRequest(viewer.session,id,accept);await load();setMsg(accept?'Collaboration request accepted.':'Request declined.')}catch(e){setMsg(e.message)}finally{setBusy('')}};
 return <main className="ct-page">
  <header className="ct-hero"><div><span>TALENT + ALUMNI NETWORK</span><h1>Stay visible. Stay connected.</h1><p>Your Canopy record can keep working for you after the cohort. You decide whether other verified WOMATE participants can discover you.</p></div><div className="ct-proof"><b>{me.completed_modules||0}/5</b><span>modules completed</span>{me.alumni&&<em>Alumni</em>}</div></header>
  <section className="ct-settings"><div><small>YOUR VISIBILITY</small><h2>Professional network settings</h2></div><div className="ct-toggleRow"><label><input type="checkbox" checked={!!me.discoverable} disabled={busy==='settings'} onChange={e=>save({discoverable:e.target.checked})}/><span>Discoverable in Canopy</span></label><label><input type="checkbox" checked={!!me.collaboration_open} disabled={busy==='settings'} onChange={e=>save({collaboration_open:e.target.checked})}/><span>Open to collaboration</span></label><label className={!me.alumni?'isDisabled':''}><input type="checkbox" checked={!!me.mentor_available} disabled={!me.alumni||busy==='settings'} onChange={e=>save({mentor_available:e.target.checked})}/><span>Available to mentor</span></label></div><div className="ct-fields"><label>Professional headline<input value={me.headline||''} maxLength={120} onChange={e=>setData(d=>({...d,me:{...d.me,headline:e.target.value}}))} onBlur={()=>save({headline:me.headline})} placeholder="Climate advocate, researcher, circular economy builder..."/></label><label>Climate interests<input value={interestList(me.climate_interests).join(', ')} onChange={e=>setData(d=>({...d,me:{...d.me,climate_interests:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)}}))} onBlur={()=>save({climate_interests:me.climate_interests})} placeholder="Adaptation, policy, waste, climate justice"/></label></div>{!me.alumni&&<p className="ct-hint">Mentor opt-in becomes available after all five modules are completed.</p>}</section>
  {(data.incoming||[]).length>0&&<section className="ct-requests"><div className="ct-sectionHead"><div><small>COLLABORATION REQUESTS</small><h2>People reaching out</h2></div></div>{data.incoming.map(r=><article key={r.id}><div><b>{r.requester_name}</b><span>{r.requester_country||'Canopy member'}</span><p>{r.message}</p></div><div><button disabled={busy===r.id} onClick={()=>respond(r.id,true)}>Accept</button><button className="ghost" disabled={busy===r.id} onClick={()=>respond(r.id,false)}>Decline</button></div></article>)}</section>}
  <section className="ct-directory"><div className="ct-sectionHead"><div><small>VERIFIED WOMATE NETWORK</small><h2>Find climate collaborators</h2></div><div className="ct-filters"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, country or climate interest"/></label><select value={country} onChange={e=>setCountry(e.target.value)}><option value="all">All countries</option>{countries.map(c=><option key={c}>{c}</option>)}</select><button className={mentorOnly?'on':''} onClick={()=>setMentorOnly(v=>!v)}>Mentors</button></div></div>
   {msg&&<p className="ct-msg">{msg}</p>}
   <div className="ct-grid">{rows.length?rows.map(x=><article key={x.user_id} className="ct-person"><div className="ct-personHead"><div className="ct-avatar">{String(x.full_name||'?').split(/\s+/).slice(0,2).map(v=>v[0]).join('').toUpperCase()}</div><div><h3>{x.full_name}</h3><p><Globe2/>{x.country||'Country not listed'}</p></div></div><p className="ct-headline">{x.headline||'Verified WOMATE Canopy participant'}</p><div className="ct-badges"><span><BadgeCheck/> {x.completed_modules||0} modules</span>{x.spotlight_count>0&&<span><Sparkles/> Spotlight</span>}{x.verified_mission&&<span><ShieldCheck/> Mission verified</span>}{x.alumni&&<span><BriefcaseBusiness/> Alumni</span>}{x.mentor_available&&<span><UsersRound/> Mentor</span>}</div>{interestList(x.climate_interests).length>0&&<div className="ct-interests">{interestList(x.climate_interests).slice(0,5).map(i=><span key={i}>{i}</span>)}</div>}{x.collaboration_open?<div className="ct-collab"><textarea rows="2" value={note[x.user_id]||''} onChange={e=>setNote(n=>({...n,[x.user_id]:e.target.value}))} placeholder="What would you like to collaborate on?"/><button disabled={busy===x.user_id} onClick={()=>send(x.user_id)}><Handshake/> Request collaboration</button></div>:<p className="ct-closed">Not currently accepting collaboration requests.</p>}</article>):<div className="ct-empty">No visible profiles match these filters yet.</div>}</div>
  </section>
 </main>
}

export function CanopyTalentAdmin({viewer}){
 const[data,setData]=useState({rows:[]}),[query,setQuery]=useState(''),[busy,setBusy]=useState(''),[msg,setMsg]=useState('');
 const load=async()=>{try{setData(await getAdminCanopyTalentNetwork(viewer.session)||{rows:[]});setMsg('')}catch(e){setMsg(e.message)}};useEffect(()=>{load()},[]);
 const rows=useMemo(()=>{const q=query.trim().toLowerCase();return(data.rows||[]).filter(x=>!q||[x.full_name,x.country,x.headline].some(v=>String(v||'').toLowerCase().includes(q)))},[data.rows,query]);
 const moderate=async x=>{const next=!x.discoverable;const remark=next?'Visibility restored by WOMATE.':'Profile hidden by WOMATE moderation.';setBusy(x.user_id);try{await setAdminCanopyTalentVisibility(viewer.session,x.user_id,next,remark);await load();setMsg(next?'Profile visibility restored.':'Profile hidden from the directory.')}catch(e){setMsg(e.message)}finally{setBusy('')}};
 return <main className="ct-page ct-admin"><header className="ct-hero"><div><span>TALENT NETWORK ADMIN</span><h1>Verified climate talent.</h1><p>Moderate discoverability without exposing private contact information.</p></div><div className="ct-proof"><b>{data.discoverable_count||0}</b><span>discoverable profiles</span></div></header><section className="ct-directory"><div className="ct-sectionHead"><div><small>NETWORK</small><h2>Participants + alumni</h2></div><label className="ct-adminSearch"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search talent"/></label></div>{msg&&<p className="ct-msg">{msg}</p>}<div className="ct-adminRows">{rows.map(x=><article key={x.user_id}><div><b>{x.full_name}</b><span>{x.country||'No country'} · {x.completed_modules||0}/5 modules{x.alumni?' · Alumni':''}</span></div><div className="ct-adminFlags">{x.spotlight_count>0&&<span>Spotlight</span>}{x.verified_mission&&<span>Mission verified</span>}{x.mentor_available&&<span>Mentor</span>}</div><button disabled={busy===x.user_id} className={x.discoverable?'warn':''} onClick={()=>moderate(x)}>{x.discoverable?'Hide':'Restore'}</button></article>)}</div></section></main>
}
