import React,{useEffect,useMemo,useState}from'react';
import{Bookmark,BriefcaseBusiness,CalendarDays,CheckCircle2,ExternalLink,Globe2,MapPin,Plus,Search,Sparkles,Star,Trash2}from'lucide-react';
import{archiveAdminCanopyOpportunity,getAdminCanopyOpportunities,getCanopyOpportunityFeed,notifyAdminCanopyOpportunity,saveAdminCanopyOpportunity,toggleCanopyOpportunitySave}from'./canopyApi';
import'./canopyOpportunityBoard.css';

const TYPES=['all','job','internship','fellowship','grant','scholarship','consultancy','conference','volunteer','other'];
const titleCase=s=>String(s||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
const deadline=d=>{if(!d)return'Open deadline';const dt=new Date(d);return Number.isNaN(dt.getTime())?'Open deadline':dt.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})};
function reasons(o,data){const out=[];if(o.global)out.push('Open globally');else if(o.country&&data.country&&o.country.trim().toLowerCase()===data.country.trim().toLowerCase())out.push('Fits your country');if(Number(o.min_module_no||0)>0&&Number(data.completed_modules||0)>=Number(o.min_module_no))out.push('Your learning progress fits');if(o.requires_spotlight&&Number(data.spotlight_count||0)>0)out.push('Spotlight experience fits');if(o.requires_verified_mission&&data.verified_mission)out.push('Verified mission experience fits');return out.slice(0,3)}

export default function CanopyOpportunityBoard({viewer}){
 const[data,setData]=useState({opportunities:[]}),[tab,setTab]=useState('for-you'),[type,setType]=useState('all'),[query,setQuery]=useState(''),[busy,setBusy]=useState(''),[msg,setMsg]=useState('');
 const load=async()=>{try{setData(await getCanopyOpportunityFeed(viewer.session)||{opportunities:[]});setMsg('')}catch(e){setMsg(e.message)}};
 useEffect(()=>{load()},[]);
 const rows=useMemo(()=>{let a=[...(data.opportunities||[])];if(tab==='for-you')a=a.filter(x=>x.matched);if(tab==='saved')a=a.filter(x=>x.saved);if(type!=='all')a=a.filter(x=>x.opportunity_type===type);const q=query.trim().toLowerCase();if(q)a=a.filter(x=>[x.title,x.organization,x.summary,x.location,x.country].some(v=>String(v||'').toLowerCase().includes(q)));return a},[data,tab,type,query]);
 const save=async o=>{setBusy(o.id);try{await toggleCanopyOpportunitySave(viewer.session,o.id);await load()}catch(e){setMsg(e.message)}finally{setBusy('')}};
 return <main className="co-page">
  <header className="co-hero"><div><span>OPPORTUNITIES</span><h1>Use what you are building.</h1><p>Explore WOMATE-reviewed opportunities and decide what is worth pursuing.</p></div><div className="co-signal"><b>{(data.opportunities||[]).filter(x=>x.matched).length}</b><span>may fit your Canopy evidence</span></div></header>
  <section className="co-tools"><div className="co-tabs"><button className={tab==='for-you'?'on':''} onClick={()=>setTab('for-you')}>For you</button><button className={tab==='all'?'on':''} onClick={()=>setTab('all')}>All opportunities</button><button className={tab==='saved'?'on':''} onClick={()=>setTab('saved')}>Saved</button></div><div className="co-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title, organisation or place"/></div></section>
  <div className="co-filters">{TYPES.map(t=><button key={t} className={type===t?'on':''} onClick={()=>setType(t)}>{t==='all'?'All types':titleCase(t)}</button>)}</div>
  {msg&&<p className="co-msg">{msg}</p>}
  <section className="co-list">{rows.length?rows.map(o=><article key={o.id} className={o.featured?'featured':''}>
    <div className="co-mark">{o.featured?<Star/>:<BriefcaseBusiness/>}</div>
    <div className="co-copy"><div className="co-meta"><span>{titleCase(o.opportunity_type)}</span>{o.global?<span><Globe2/>Global</span>:o.country?<span><MapPin/>{o.country}</span>:null}<span><CalendarDays/>{deadline(o.deadline_at)}</span></div><h2>{o.title}</h2><h3>{o.organization}</h3><p>{o.summary}</p>{o.compensation&&<small className="co-pay">{o.compensation}</small>}{o.matched&&<div className="co-reasons">{reasons(o,data).map(r=><span key={r}><CheckCircle2/>{r}</span>)}</div>}</div>
    <div className="co-actions"><button aria-label={o.saved?'Remove saved opportunity':'Save opportunity'} className={o.saved?'saved':''} disabled={busy===o.id} onClick={()=>save(o)}><Bookmark/></button><a href={o.url} target="_blank" rel="noreferrer">View opportunity <ExternalLink/></a></div>
  </article>):<div className="co-empty"><Sparkles/><h2>No opportunities here yet.</h2><p>Try another view or check again when WOMATE publishes more opportunities.</p></div>}</section>
 </main>
}

const emptyForm={id:null,title:'',organization:'',opportunity_type:'fellowship',summary:'',url:'',location:'',country:'',global:true,compensation:'',deadline_at:'',min_module_no:0,requires_spotlight:false,requires_verified_mission:false,featured:false,published:false};
export function CanopyOpportunityAdmin({viewer}){
 const[rows,setRows]=useState([]),[form,setForm]=useState(emptyForm),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const load=async()=>{try{setRows(await getAdminCanopyOpportunities(viewer.session)||[]);setMsg('')}catch(e){setMsg(e.message)}};useEffect(()=>{load()},[]);
 const edit=o=>setForm({...emptyForm,...o,deadline_at:o.deadline_at?new Date(o.deadline_at).toISOString().slice(0,16):''});
 const save=async e=>{e.preventDefault();setBusy(true);setMsg('');try{await saveAdminCanopyOpportunity(viewer.session,{...form,deadline_at:form.deadline_at?new Date(form.deadline_at).toISOString():null});setForm(emptyForm);await load();setMsg('Opportunity saved.')}catch(err){setMsg(err.message)}finally{setBusy(false)}};
 const archive=async id=>{if(!confirm('Archive this opportunity?'))return;setBusy(true);try{await archiveAdminCanopyOpportunity(viewer.session,id);await load();setMsg('Opportunity archived.')}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 const notify=async id=>{setBusy(true);try{const n=await notifyAdminCanopyOpportunity(viewer.session,id);setMsg('Notification sent to '+Number(n||0)+' matching learner(s).')}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 return <section className="coa-page"><header><div><span>OPPORTUNITY LAYER</span><h2>Publish opportunities learners can actually use.</h2><p>Canopy uses existing evidence only to order relevance. Learners decide what to pursue.</p></div><button onClick={()=>setForm(emptyForm)}><Plus/>New</button></header>{msg&&<p className="coa-msg">{msg}</p>}
  <div className="coa-layout"><form onSubmit={save} className="coa-form"><h3>{form.id?'Edit opportunity':'Add opportunity'}</h3><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Organisation<input value={form.organization} onChange={e=>setForm({...form,organization:e.target.value})} required/></label><div className="coa-two"><label>Type<select value={form.opportunity_type} onChange={e=>setForm({...form,opportunity_type:e.target.value})}>{TYPES.filter(x=>x!=='all').map(x=><option key={x} value={x}>{titleCase(x)}</option>)}</select></label><label>Minimum completed module<select value={form.min_module_no} onChange={e=>setForm({...form,min_module_no:Number(e.target.value)})}>{[0,1,2,3,4,5].map(n=><option key={n} value={n}>{n===0?'None':'Module '+String(n).padStart(2,'0')}</option>)}</select></label></div><label>Summary<textarea value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})} required/></label><label>Opportunity URL<input type="url" value={form.url} onChange={e=>setForm({...form,url:e.target.value})} required/></label><div className="coa-two"><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Country<input value={form.country} disabled={form.global} onChange={e=>setForm({...form,country:e.target.value})}/></label></div><div className="coa-two"><label>Compensation / funding<input value={form.compensation} onChange={e=>setForm({...form,compensation:e.target.value})} placeholder="Optional"/></label><label>Deadline<input type="datetime-local" value={form.deadline_at} onChange={e=>setForm({...form,deadline_at:e.target.value})}/></label></div><div className="coa-checks"><label><input type="checkbox" checked={form.global} onChange={e=>setForm({...form,global:e.target.checked})}/>Global</label><label><input type="checkbox" checked={form.requires_spotlight} onChange={e=>setForm({...form,requires_spotlight:e.target.checked})}/>Requires Spotlight</label><label><input type="checkbox" checked={form.requires_verified_mission} onChange={e=>setForm({...form,requires_verified_mission:e.target.checked})}/>Requires verified mission</label><label><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/>Featured</label><label><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/>Published</label></div><button className="coa-save" disabled={busy}>{busy?'Saving...':'Save opportunity'}</button></form>
  <div className="coa-list">{rows.length?rows.map(o=><article key={o.id} className={o.archived?'archived':''}><div><small>{titleCase(o.opportunity_type)} {o.published?' / Published':' / Draft'}</small><h3>{o.title}</h3><p>{o.organization}{o.deadline_at?' / '+deadline(o.deadline_at):''}</p></div><div className="coa-rowactions"><button onClick={()=>edit(o)}>Edit</button>{o.published&&!o.archived&&<button onClick={()=>notify(o.id)} disabled={busy}>Notify matches</button>}{!o.archived&&<button onClick={()=>archive(o.id)} disabled={busy}><Trash2/>Archive</button>}</div></article>):<div className="coa-empty">No opportunities yet.</div>}</div></div>
 </section>
}
