import React,{useEffect,useMemo,useState}from'react';
import{BadgeCheck,BriefcaseBusiness,Camera,CheckCircle2,Globe2,Handshake,Search,ShieldCheck,Sparkles,UsersRound}from'lucide-react';
import{getCanopyTalentNetwork,saveCanopyTalentSettings,sendCanopyCollaborationRequest,respondCanopyCollaborationRequest,getAdminCanopyTalentNetwork,setAdminCanopyTalentVisibility,canopyProfilePhotoUrl}from'./canopyApi';
import'./canopyTalentNetwork.css';

const clean=v=>String(v||'').trim();
const interestList=v=>Array.isArray(v)?v:[];
const statusLabel=x=>x.visible?'LIVE':x.approved_for_discovery?(x.profile_ready?'APPROVED':'PROFILE REQUIRED'):x.eligible_for_discovery?'AWAITING APPROVAL':'NOT ELIGIBLE';

export default function CanopyTalentNetwork({viewer}){
 const[data,setData]=useState({directory:[],incoming:[],outgoing:[],me:{}}),[query,setQuery]=useState(''),[country,setCountry]=useState('all'),[achievement,setAchievement]=useState('all'),[mentorOnly,setMentorOnly]=useState(false),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[note,setNote]=useState({});
 const load=async()=>{try{setData(await getCanopyTalentNetwork(viewer.session)||{directory:[],incoming:[],outgoing:[],me:{}});setMsg('')}catch(e){setMsg(e.message)}};
 useEffect(()=>{load()},[]);
 const me=data.me||{};
 const countries=useMemo(()=>Array.from(new Set((data.directory||[]).map(x=>x.country).filter(Boolean))).sort(),[data.directory]);
 const rows=useMemo(()=>{const q=query.trim().toLowerCase();return(data.directory||[]).filter(x=>
   (country==='all'||x.country===country)&&
   (!mentorOnly||x.mentor_available)&&
   (achievement==='all'||(achievement==='modules'&&x.all_modules_completed)||(achievement==='mission'&&x.mission_completed)||(achievement==='final'&&x.final_team_completed)||(achievement==='spotlight'&&x.spotlight_count>0))&&
   (!q||[x.full_name,x.country,x.headline,...interestList(x.climate_interests)].some(v=>String(v||'').toLowerCase().includes(q)))
 )},[data.directory,query,country,achievement,mentorOnly]);
 const save=async patch=>{setBusy('settings');try{await saveCanopyTalentSettings(viewer.session,{discoverable:me.discoverable,mentorAvailable:patch.mentor_available??me.mentor_available,collaborationOpen:patch.collaboration_open??me.collaboration_open,headline:patch.headline??me.headline,interests:patch.climate_interests??interestList(me.climate_interests)});await load();setMsg('Talent profile updated.')}catch(e){setMsg(e.message)}finally{setBusy('')}};
 const send=async userId=>{const text=clean(note[userId]);if(!text){setMsg('Add a short collaboration note first.');return}setBusy(userId);try{await sendCanopyCollaborationRequest(viewer.session,userId,text);setNote(n=>({...n,[userId]:''}));await load();setMsg('Collaboration request sent.')}catch(e){setMsg(e.message)}finally{setBusy('')}};
 const respond=async(id,accept)=>{setBusy(id);try{await respondCanopyCollaborationRequest(viewer.session,id,accept);await load();setMsg(accept?'Collaboration request accepted.':'Request declined.')}catch(e){setMsg(e.message)}finally{setBusy('')}};
 return <main className="ct-page">
  <header className="ct-hero"><div><span>TALENT DISCOVERY</span><h1>Verified people. Real evidence.</h1><p>Talent Discovery is curated by WOMATE. A profile appears only after Admin approval, verified achievement and completion of the public professional profile.</p></div><div className="ct-proof"><b>{me.completed_modules||0}/5</b><span>modules completed</span>{me.mission_completed&&<em>Mission Completed</em>}</div></header>

  <section className={'ct-approvalPanel '+(me.visible?'isLive':me.approved_for_discovery?'isApproved':'')}>
   <div className="ct-approvalIcon">{me.visible?<CheckCircle2/>:me.approved_for_discovery?<Camera/>:<ShieldCheck/>}</div>
   <div><small>YOUR TALENT DISCOVERY STATUS</small><h2>{me.visible?'Your profile is live in Talent Discovery':me.approved_for_discovery?'WOMATE approved you — finish your profile':'WOMATE approval is required'}</h2>
   <p>{me.visible?'Your verified profile is now discoverable by the WOMATE network.':me.approved_for_discovery?'Add a profile image, professional headline and climate interests. Once all required profile details are complete, your approved profile appears automatically.':me.eligible_for_discovery?'You meet the achievement requirement. Admin must approve your profile before it can appear in Talent Discovery.':'Talent Discovery eligibility unlocks after all five modules are completed or WOMATE approves an individual Mission contribution as Mission Completed.'}</p></div>
   {!me.profile_ready&&me.approved_for_discovery&&<button onClick={()=>{window.history.pushState({},'','/canopy/profile');window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo({top:0,behavior:'smooth'})}}>Complete profile</button>}
  </section>

  <section className="ct-settings"><div><small>YOUR PROFESSIONAL PROFILE</small><h2>Discovery details</h2><p className="ct-hint">Visibility is controlled by WOMATE approval. You control your professional description, interests and collaboration availability.</p></div>
   <div className="ct-statusStrip"><span className={me.approved_for_discovery?'ok':'wait'}><ShieldCheck/> {me.approved_for_discovery?'Admin approved':'Admin approval pending'}</span><span className={me.eligible_for_discovery?'ok':'wait'}><BadgeCheck/> {me.eligible_for_discovery?'Achievement eligible':'Achievement gate pending'}</span><span className={me.avatar_path?'ok':'wait'}><Camera/> {me.avatar_path?'Photo added':'Photo required'}</span><span className={me.profile_ready?'ok':'wait'}><CheckCircle2/> {me.profile_ready?'Profile complete':'Profile incomplete'}</span></div>
   <div className="ct-toggleRow"><label><input type="checkbox" checked={!!me.collaboration_open} disabled={busy==='settings'} onChange={e=>save({collaboration_open:e.target.checked})}/><span>Open to collaboration</span></label><label className={!me.alumni?'isDisabled':''}><input type="checkbox" checked={!!me.mentor_available} disabled={!me.alumni||busy==='settings'} onChange={e=>save({mentor_available:e.target.checked})}/><span>Available to mentor</span></label></div>
   <div className="ct-fields"><label>Professional headline<input value={me.headline||''} maxLength={120} onChange={e=>setData(d=>({...d,me:{...d.me,headline:e.target.value}}))} onBlur={()=>save({headline:me.headline})} placeholder="Climate advocate, researcher, circular economy builder..."/></label><label>Climate interests<input value={interestList(me.climate_interests).join(', ')} onChange={e=>setData(d=>({...d,me:{...d.me,climate_interests:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)}}))} onBlur={()=>save({climate_interests:me.climate_interests})} placeholder="Adaptation, policy, waste, climate justice"/></label></div>
   {!me.avatar_path&&<p className="ct-profileAction"><Camera/> Add your professional image from <button onClick={()=>{window.history.pushState({},'','/canopy/profile');window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo({top:0,behavior:'smooth'})}}>Profile & settings</button>.</p>}
  </section>

  {(data.incoming||[]).length>0&&<section className="ct-requests"><div className="ct-sectionHead"><div><small>COLLABORATION REQUESTS</small><h2>People reaching out</h2></div></div>{data.incoming.map(r=><article key={r.id}><div><b>{r.requester_name}</b><span>{r.requester_country||'Canopy member'}</span><p>{r.message}</p></div><div><button disabled={busy===r.id} onClick={()=>respond(r.id,true)}>Accept</button><button className="ghost" disabled={busy===r.id} onClick={()=>respond(r.id,false)}>Decline</button></div></article>)}</section>}

  <section className="ct-directory"><div className="ct-sectionHead"><div><small>WOMATE APPROVED TALENT</small><h2>Talent Discovery</h2><p>Only approved, achievement-qualified, profile-ready participants appear here.</p></div></div>
   <div className="ct-filterBar">
    <label className="ct-searchWide"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, country, headline or interest"/></label>
    <select value={country} onChange={e=>setCountry(e.target.value)}><option value="all">All countries</option>{countries.map(c=><option key={c}>{c}</option>)}</select>
    <select value={achievement} onChange={e=>setAchievement(e.target.value)}><option value="all">All achievements</option><option value="modules">All modules completed</option><option value="mission">Mission Completed</option><option value="final">Final Mission team</option><option value="spotlight">Canopy Spotlight</option></select>
    <button className={mentorOnly?'on':''} onClick={()=>setMentorOnly(v=>!v)}>Mentors</button>
   </div>
   {msg&&<p className="ct-msg">{msg}</p>}
   <div className="ct-grid">{rows.length?rows.map(x=><article key={x.user_id} className="ct-person"><div className="ct-personHead"><div className="ct-avatar"><img src={canopyProfilePhotoUrl(x.avatar_path)} alt={`${x.full_name} profile`} loading="lazy"/></div><div><h3>{x.full_name}</h3><p><Globe2/>{x.country}</p></div></div><p className="ct-headline">{x.headline}</p><div className="ct-badges">{x.all_modules_completed&&<span><BadgeCheck/> All modules completed</span>}{x.mission_completed&&<span className="mission"><ShieldCheck/> Mission Completed</span>}{x.final_team_completed&&<span className="mission"><UsersRound/> Final Mission team</span>}{x.spotlight_count>0&&<span><Sparkles/> Spotlight</span>}{x.mentor_available&&<span><BriefcaseBusiness/> Mentor</span>}</div>{interestList(x.climate_interests).length>0&&<div className="ct-interests">{interestList(x.climate_interests).slice(0,6).map(i=><span key={i}>{i}</span>)}</div>}{x.collaboration_open?<div className="ct-collab"><textarea rows="2" value={note[x.user_id]||''} onChange={e=>setNote(n=>({...n,[x.user_id]:e.target.value}))} placeholder="What would you like to collaborate on?"/><button disabled={busy===x.user_id} onClick={()=>send(x.user_id)}><Handshake/> Request collaboration</button></div>:<p className="ct-closed">Not currently accepting collaboration requests.</p>}</article>):<div className="ct-empty">No approved Talent Discovery profiles match these filters.</div>}</div>
  </section>
 </main>
}

export function CanopyTalentAdmin({viewer}){
 const[data,setData]=useState({rows:[]}),[query,setQuery]=useState(''),[status,setStatus]=useState('eligible'),[achievement,setAchievement]=useState('all'),[busy,setBusy]=useState(''),[msg,setMsg]=useState('');
 const load=async()=>{try{setData(await getAdminCanopyTalentNetwork(viewer.session)||{rows:[]});setMsg('')}catch(e){setMsg(e.message)}};useEffect(()=>{load()},[]);
 const rows=useMemo(()=>{const q=query.trim().toLowerCase();return(data.rows||[]).filter(x=>{
   const statusOk=status==='all'||(status==='live'&&x.visible)||(status==='approved'&&x.approved_for_discovery&&!x.visible)||(status==='eligible'&&x.eligible_for_discovery&&!x.approved_for_discovery)||(status==='ineligible'&&!x.eligible_for_discovery);
   const achievementOk=achievement==='all'||(achievement==='modules'&&x.all_modules_completed)||(achievement==='mission'&&x.mission_completed)||(achievement==='final'&&x.final_team_completed);
   return statusOk&&achievementOk&&(!q||[x.full_name,x.country,x.headline].some(v=>String(v||'').toLowerCase().includes(q)));
 })},[data.rows,query,status,achievement]);
 const moderate=async x=>{const next=!x.approved_for_discovery;const remark=next?'Approved by WOMATE for Talent Discovery.':'Talent Discovery approval revoked by WOMATE.';setBusy(x.user_id);try{await setAdminCanopyTalentVisibility(viewer.session,x.user_id,next,remark);await load();setMsg(next?'Talent Discovery approval saved. The learner has been notified to complete her profile and image.':'Talent Discovery approval revoked.')}catch(e){setMsg(e.message)}finally{setBusy('')}};
 return <main className="ct-page ct-admin"><header className="ct-hero"><div><span>TALENT DISCOVERY ADMIN</span><h1>Approve evidence-backed talent.</h1><p>Approval alone does not publish a profile. A learner must also have all five modules completed or Mission Completed, plus a complete professional profile and image.</p></div><div className="ct-proof"><b>{data.visible_count||0}</b><span>live profiles</span><em>{data.approved_count||0} approved</em></div></header>
  <section className="ct-adminSummary"><span><b>{(data.rows||[]).filter(x=>x.eligible_for_discovery&&!x.approved_for_discovery).length}</b> awaiting approval</span><span><b>{(data.rows||[]).filter(x=>x.approved_for_discovery&&!x.profile_ready).length}</b> approved · profile needed</span><span><b>{data.visible_count||0}</b> live</span><span><b>{(data.rows||[]).filter(x=>x.mission_completed).length}</b> Mission Completed</span></section>
  <section className="ct-directory"><div className="ct-sectionHead"><div><small>APPROVAL QUEUE</small><h2>Talent Discovery controls</h2></div></div>
   <div className="ct-filterBar ct-adminFilterBar"><label className="ct-searchWide"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search learner, country or headline"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="eligible">Eligible · awaiting approval</option><option value="approved">Approved · not live</option><option value="live">Live profiles</option><option value="ineligible">Not yet eligible</option><option value="all">All learners</option></select><select value={achievement} onChange={e=>setAchievement(e.target.value)}><option value="all">All achievements</option><option value="modules">All modules completed</option><option value="mission">Mission Completed</option><option value="final">Final Mission team</option></select></div>
   {msg&&<p className="ct-msg">{msg}</p>}
   <div className="ct-adminRows">{rows.map(x=><article key={x.user_id} className={x.visible?'isLive':''}><div className="ct-adminPerson"><div className="ct-adminAvatar">{x.avatar_path?<img src={canopyProfilePhotoUrl(x.avatar_path)} alt=""/>:<span>{String(x.full_name||'?').slice(0,1)}</span>}</div><div><b>{x.full_name}</b><span>{x.country||'Country missing'} · {x.completed_modules||0}/5 modules</span><small>{statusLabel(x)}</small></div></div><div className="ct-adminFlags">{x.all_modules_completed&&<span>All modules</span>}{x.mission_completed&&<span>Mission Completed</span>}{x.final_team_completed&&<span>Final Mission team</span>}{x.spotlight_count>0&&<span>Spotlight</span>}{!x.avatar_path&&<span className="warn">Photo missing</span>}{!x.profile_ready&&<span className="warn">Profile incomplete</span>}</div><button disabled={busy===x.user_id||(!x.approved_for_discovery&&!x.eligible_for_discovery)} className={x.approved_for_discovery?'warn':''} onClick={()=>moderate(x)}>{x.approved_for_discovery?'Revoke approval':'Approve for Talent Discovery'}</button></article>)}{!rows.length&&<div className="ct-empty">No learners match these filters.</div>}</div>
  </section>
 </main>
}
