const fs=require('fs');
const path=require('path');
const root=process.cwd();
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const checks=[];
const check=(name,ok)=>checks.push([name,Boolean(ok)]);
const app=read('src/canopy/CanopyApp.jsx');
const team=read('src/canopy/CanopyTeamAccess.jsx');
const api=read('src/canopy/canopyTeamAccessApi.js');
const data=read('src/canopy/canopyData.js');
const assignments=read('src/canopy/CanopyAssignmentsV2.jsx');
const css=read('src/canopy/canopy.css');
const sql=read('CANOPY_OPERATIONS/WOMATE_CANOPY_MASTER_2026.sql');
check('participant classroom preserved',app.includes("'/canopy/classroom'"));
check('tester isolated',app.includes('p.viewmultimedia@gmail.com')&&sql.includes('isolated Canopy tester account'));
check('team-code field',app.includes('Team Access Code')&&app.includes('canopy_team_access_code_pending'));
check('programme manager dashboard',app.includes('programme_manager')&&team.includes('Programme & Monitoring Manager'));
check('programme operations deputy',app.includes('programme_operations')&&team.includes('Programme Operations Deputy'));
check('module coordinator',app.includes('module_coordinator')&&team.includes('Learning Experience Coordinator'));
check('learning experience fellow',app.includes('learning_fellow')&&team.includes('Learning Experience Fellow'));
check('admin Team Access workspace',app.includes('/canopy/manage/team-access')&&team.includes('Generate Cohort 2 team pack'));
check('22-person team pack',sql.includes("'count',22")&&team.includes('22 separate codes'));
check('five module-bound coordinator slots',sql.includes("foreach mod in array array['module-01','module-02','module-03','module-04','module-05']"));
check('three fellows per module',sql.includes('for i in 1..3 loop'));
check('single-use code hashing',sql.includes("digest(upper(trim(raw)),'sha256')")&&sql.includes("max_uses integer not null default 1"));
check('staff audit log',sql.includes('canopy_team_audit_log'));
check('Canopy Spotlight',team.includes('CANOPY SPOTLIGHT')&&sql.includes('canopy_spotlight_nominations'));
check('programme manager final assessment authority',sql.includes("m.role='programme_manager'")&&sql.includes('Only an authorised WOMATE Programme Manager can review assignments'));
check('status/assessment manual-review fix',sql.includes("status=v_status,assessment_status=p_decision"));
check('tester notification score sync',sql.includes('canopy_sync_tester_assignment_score_notification'));
check('Jotform hidden from knowledge checks',app.includes('canopyKnowledgeCheck')&&app.includes('CANOPY_AGENT_SCRIPT'));
check('all five Synthesia videos', ['78a7b03f','4d2a680b','03d27d73','d4b0cb1a','0eb25129'].every(x=>data.includes(x)));
check('module-specific assignments',assignments.includes('canopyModules2026')&&assignments.includes('paragraphPrompt')&&assignments.includes('canvasBrief'));
check('five puzzle formats', ['Unscramble','Match the words','Mini crossword','Anagram challenge','Leadership pathway jigsaw'].every(x=>assignments.includes(x)));
check('lemon completed check',css.includes('#C6FF52'));
const failed=checks.filter(([,ok])=>!ok);
for(const [name,ok] of checks)console.log(`${ok?'PASS':'FAIL'}  ${name}`);
console.log(`\n${checks.length-failed.length}/${checks.length} checks passed.`);
if(failed.length)process.exit(1);

