import React,{useState,useEffect,useRef}from'react';
import{createRoot}from'react-dom/client';
import{ArrowUpRight,Menu,X,ChevronRight,ChevronDown,ChevronLeft,Leaf,Users,Award,Microscope,Quote,Sparkles,ShieldCheck,Brain,MoveRight,Play,Heart,Radio,Globe2,BookOpen}from'lucide-react';
import'./style.css';

const pages={
'/':{k:'WOMATE',title:'African women leading climate action.',accent:'Knowledge. Technology. Community.',intro:'We equip African women to understand climate systems, lead resilient communities and shape the institutions building our shared future.',type:'home'},
'/she-leads':{k:'SHE LEADS',title:'She Leads Climate Mentorship.',accent:'Climate knowledge. Leadership. Agency.',intro:'A learning and leadership pathway designed for young African women ready to move from climate concern to credible action.',type:'she'},
'/wok-action':{k:'WOK—ACTION',title:'Women’s local knowledge for climate adaptation.',accent:'Knowledge held by women is climate infrastructure.',intro:'We document, protect and activate women’s community knowledge as living evidence for locally grounded adaptation.',type:'wok'},
'/circle':{k:'THE WOMATE CIRCLE',title:'A climate community for women.',accent:'Belong. Build. Lead.',intro:'A professional and community network where women access opportunities, peers, learning, visibility and long-term climate leadership support.',type:'circle'},
'/research':{k:'RESEARCH',title:'We Research. You Lead.',accent:'Evidence built for better climate decisions.',intro:'Gender-responsive climate intelligence, programme design and evidence support for institutions working across Africa.',type:'research'},
'/resilient-minds':{k:'RESILIENT MINDS',title:'To See What Is Hidden.',accent:'Climate resilience must include mental health.',intro:'Support, research and care pathways addressing the emotional and psychological costs of climate disruption.',type:'minds'},
'/honours':{k:'CLIMATE HONOURS',title:'Amplify the Untold.',accent:'Recognising women moving Africa’s climate future forward.',intro:'An annual platform documenting, celebrating and connecting women whose climate leadership deserves to be seen.',type:'honours'},
'/leadership':{k:'LEADERSHIP',title:'Driving Inclusive Climate Action with Technology.',accent:'Women-led. Africa-rooted. Future-facing.',intro:'A multidisciplinary leadership team connecting climate science, technology, research, community practice and storytelling.',type:'leadership'},
'/funding':{k:'FUNDING SUPPORT',title:'Grant Application Support Programme 2026',accent:'Make strong climate work easier to fund.',intro:'Structured application support for African women founders building credible, investable and grant-ready climate initiatives.',type:'funding'},
'/womateer':{k:'WOMATEER',title:'Elevate Your Impact as a WOMATEER',accent:'Volunteer talent. Serious climate impact.',intro:'Contribute professional skill to a women-led climate organisation building knowledge, visibility and resilience across Africa.',type:'volunteer'},
'/merchandise':{k:'THE VAULT',title:'Wear the work.',accent:'WOMATE objects for climate community.',intro:'Limited pieces that carry the identity, conversations and conviction of women leading climate action.',type:'merch'}
};
const nav=[['She Leads','/she-leads'],['WoK-Action','/wok-action'],['Circle','/circle'],['Research','/research'],['Resilient Minds','/resilient-minds'],['Honours','/honours']];
function Link({to,children,className=''}){return <a className={className} href={to}>{children}</a>}
function Header(){const[open,setOpen]=useState(false);return <><header className="globalHeader"><Link to="/" className="brand"><img src="/assets/img/logo.svg"/></Link><nav className="desktopNav"><div className="navGroup"><button className="navTrigger">Our work <ChevronDown size={15}/></button><div className="megaMenu workMenu"><div className="megaIntro"><span>WOMATE ECOSYSTEM</span><strong>Women leading climate action.</strong><p>Knowledge, evidence, community and recognition designed around African women.</p></div><div className="megaLinks"><div><span className="megaLabel">LEARN & LEAD</span><Link to="/she-leads"><b>She Leads</b><small>Climate mentorship & leadership</small></Link><Link to="/circle"><b>The WOMATE Circle</b><small>Community & professional network</small></Link></div><div><span className="megaLabel">KNOWLEDGE & CARE</span><Link to="/wok-action"><b>WoK—Action</b><small>Women’s local climate knowledge</small></Link><Link to="/research"><b>Research</b><small>Gender-responsive evidence</small></Link><Link to="/resilient-minds"><b>Resilient Minds</b><small>Climate & mental-health support</small></Link></div></div><Link to="/honours" className="megaFeature"><span>CLIMATE HONOURS</span><strong>Amplify the Untold.</strong><ArrowUpRight size={18}/></Link></div></div><Link to="/honours" className="desktopDirect">Climate Honours</Link><div className="navGroup"><button className="navTrigger">Organisation <ChevronDown size={15}/></button><div className="megaMenu orgMenu"><div className="megaIntro"><span>ABOUT WOMATE</span><strong>Africa-rooted. Future-facing.</strong><p>Meet the people, partnerships and opportunities behind the work.</p></div><div className="orgLinks"><Link to="/leadership"><b>Our organisation</b><small>Leadership & institutional direction</small></Link><Link to="/funding"><b>Funding support</b><small>Grant application programme</small></Link><Link to="/womateer"><b>WOMATEER</b><small>Volunteer your professional skill</small></Link><Link to="/merchandise"><b>The Vault</b><small>WOMATE merchandise</small></Link></div></div></div></nav><div className="headright"><Link to="/circle" className="headerJoin">Join the community <ArrowUpRight size={16}/></Link></div><button className="menu" aria-label="Open navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>{open&&<div className="mobileNav">{[...nav,['Leadership','/leadership'],['Funding','/funding'],['WOMATEER','/womateer'],['The Vault','/merchandise']].map(n=><Link key={n[1]} to={n[1]}>{n[0]}<ChevronRight/></Link>)}</div>}</>}

const heroAssets={
home:'/assets/hero/home-africa-map.png',
she:'/assets/hero/she-leads.png',
wok:'/assets/hero/wok-action.png',
circle:'/assets/hero/circle.png',
research:'/assets/hero/research.png',
minds:'/assets/hero/resilient-minds.png',
honours:'/assets/hero/honours.png',
leadership:'/assets/hero/leadership.png',
funding:'/assets/hero/funding.png',
volunteer:'/assets/hero/womateer.png.svg',
merch:'/assets/img/merch/13.png'
};

const stats=[
{value:40,label:'graduates'},
{value:15,label:'countries'},
{value:18,label:'honourees',suffix:'+'},
{value:1000,label:'lives reached',compact:true,suffix:'+'}
];
function AnimatedStat({value,label,suffix='',compact=false}){const ref=useRef(null);const[count,setCount]=useState(0);const[started,setStarted]=useState(false);useEffect(()=>{const el=ref.current;if(!el)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){setStarted(true);observer.disconnect()}},{threshold:.45});observer.observe(el);return()=>observer.disconnect()},[]);useEffect(()=>{if(!started)return;let frame;const duration=1350;const start=performance.now();const tick=now=>{const progress=Math.min(1,(now-start)/duration);const eased=1-Math.pow(1-progress,3);setCount(Math.round(value*eased));if(progress<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[started,value]);let display=compact&&count>=1000?'1k':count.toLocaleString();return <div ref={ref} className="animatedStat"><strong>{display}{suffix}</strong><span>{label}</span></div>}
const programs=[
['She Leads','Climate knowledge and leadership for young African women.','/she-leads',<Users size={22}/>,heroAssets?.she],
['WoK—Action','Women’s local knowledge as living climate infrastructure.','/wok-action',<Leaf size={22}/>,heroAssets?.wok],
['The WOMATE Circle','A professional climate community built around women.','/circle',<Globe2 size={22}/>,heroAssets?.circle],
['Research','Gender-responsive climate evidence for better decisions.','/research',<Microscope size={22}/>,heroAssets?.research],
['Resilient Minds','Climate resilience that includes mental health and care.','/resilient-minds',<Brain size={22}/>,heroAssets?.minds],
['Climate Honours','Recognition for women moving Africa’s climate future forward.','/honours',<Award size={22}/>,heroAssets?.honours]
];

const impactReportPages=[
{n:'01',kind:'cover',content:<><span className="reportEst">EST. 2025</span><div className="reportWordmark">WOMATE</div><h2>ANNUAL<br/>IMPACT REPORT</h2><div className="reportRule"/><h3>DRIVING INCLUSIVE CLIMATE ACTION WITH TECHNOLOGY</h3><div className="reportCoverFoot"><span>AFRICA · WOMEN · CLIMATE · TECHNOLOGY</span><span>2025</span></div></>},
{n:'02',kind:'blueprint',content:<><span className="reportKicker">THE BLUEPRINT</span><blockquote>“To build a world where African women lead climate action through innovative, tech-driven solutions.”</blockquote><p>We equip women with the technology, training, and community support required to flip the script on climate leadership.</p><div className="legacyTitle">2025 Legacy</div><div className="legacyGrid"><div><b>40</b><span>She Leads<br/>Graduates</span></div><div><b>15</b><span>African<br/>Countries</span></div><div><b>18+</b><span>Climate<br/>Honors</span></div><div><b>1k+</b><span>Lives<br/>Impacted</span></div></div></>},
{n:'03',kind:'pillars',content:<><span className="reportKicker">HOW WOMATE MOVES</span><div className="reportPillars"><article><b>01.</b><h3>Community</h3><p>Safe digital hubs on LinkedIn & WhatsApp for mentorship and collaboration.</p></article><article><b>02.</b><h3>Storytelling</h3><p>Creative media spotlighting the remarkable work of African women innovators.</p></article><article><b>03.</b><h3>Capacity Building</h3><p>Fellowships and webinars tailored for women navigating climate leadership paths.</p></article><article><b>04.</b><h3>Advocacy</h3><p>Partnering with NGOs and tech hubs to influence gender-responsive policies.</p></article></div></>},
{n:'04',kind:'technology',content:<><span className="reportKicker">TECH INTEGRATION</span><h2>Local climate intelligence.<br/><em>Digital possibility.</em></h2><p>We bridge local climate issues with digital solutions—from precision agriculture projects to inclusive education platforms.</p><blockquote>“Putting the mic, the power, and the future in the hands of women.”</blockquote><div className="whyPanel"><span>THE “WHY”</span><h3>Climate change hits women the hardest, yet they are the least included.</h3><strong>We don't believe in token inclusion. We believe in full leadership.</strong></div></>},
{n:'05',kind:'sdg',content:<><span className="reportKicker">GLOBAL ALIGNMENT</span><h2>Five goals.<br/>One connected future.</h2><p>WOMATE's 2026 ecosystem directly accelerates five critical UN Sustainable Development Goals.</p><div className="sdgGrid"><div><span>⚖️</span><b>SDG 5</b><small>Gender Equality</small></div><div><span>💻</span><b>SDG 9</b><small>Industry, Innovation & Tech</small></div><div><span>🌍</span><b>SDG 13</b><small>Climate Action</small></div><div><span>🤝</span><b>SDG 17</b><small>Partnerships for the Goals</small></div><div><span>🎓</span><b>SDG 4</b><small>Quality Education & Training</small></div></div><div className="reportConnect"><div><span>BRIDGE THE GAP</span><h3>Let's align for the SDGs.</h3><p>We are calling for like-minded partners to lead 2026.</p></div><a href="https://www.linkedin.com/company/womeninclimategh" target="_blank" rel="noreferrer">Connect with us <ArrowUpRight size={17}/></a></div></>}
];
function ImpactReport({open,onClose}){const[page,setPage]=useState(0);useEffect(()=>{if(!open)return;setPage(0);const key=e=>{if(e.key==='Escape')onClose();if(e.key==='ArrowRight')setPage(v=>Math.min(impactReportPages.length-1,v+1));if(e.key==='ArrowLeft')setPage(v=>Math.max(0,v-1))};document.addEventListener('keydown',key);document.body.classList.add('reportOpen');return()=>{document.removeEventListener('keydown',key);document.body.classList.remove('reportOpen')}},[open,onClose]);if(!open)return null;const p=impactReportPages[page];return <div className="reportOverlay" role="dialog" aria-modal="true" aria-label="WOMATE 2025 Annual Impact Report"><button className="reportBackdrop" onClick={onClose} aria-label="Close report"/><div className="reportShell"><div className="reportTopbar"><div><BookOpen size={17}/><span>WOMATE · ANNUAL IMPACT REPORT · 2025</span></div><button onClick={onClose} aria-label="Close report"><X/></button></div><div className={'reportPage report-'+p.kind} key={page}>{p.content}<span className="reportPageNo">{p.n} / 05</span></div><div className="reportControls"><button onClick={()=>setPage(v=>Math.max(0,v-1))} disabled={page===0}><ChevronLeft/> Previous</button><div className="reportDots">{impactReportPages.map((_,i)=><button key={i} className={i===page?'active':''} onClick={()=>setPage(i)} aria-label={'Go to report page '+(i+1)}/>)}</div><button onClick={()=>setPage(v=>Math.min(impactReportPages.length-1,v+1))} disabled={page===impactReportPages.length-1}>Next <ChevronRight/></button></div></div></div>}

function HeroVisual({type}){let src=heroAssets[type]||heroAssets.home;return <div className={'heroVisual hv-'+type}><img className="heroCharacter" src={src} alt=""/>{type==='home'&&<div className="communityOverlay"><div className="communityPulse"><Radio size={14}/><span>WOMATE CIRCLE · LIVE COMMUNITY</span></div><div className="communityRow"><div className="communityAvatars"><img src="/assets/img/team/r.jpg"/><img src="/assets/img/team/asaa.jpeg"/><img src="/assets/img/testi/19.svg"/></div><div><strong>Women connecting across 15 countries</strong><small>WhatsApp mentorship · peer exchange · opportunities</small></div></div></div>}</div>}
function Hero({p,onExplore}){return <section className={'hero hero-'+p.type}><div className="heroTop"><div className="heroCopy"><h1>{p.title}</h1><div className="actions">{onExplore?<button type="button" onClick={onExplore} className="pill lime heroExplore">Explore the work <BookOpen size={16}/></button>:<a href="#content" className="pill lime">Explore the work <ArrowUpRight size={16}/></a>}<Link to="/circle" className="pill ghost">Join the community</Link></div></div><HeroVisual type={p.type}/></div></section>}

const testimonials=[
['The programme deepened my understanding of climate change, resilience and advocacy, and strengthened my commitment to women and youth engagement.','Betty Mulenga','2025 She Leads Alumni · Zambia','/assets/img/testi/19.svg'],
['The mentorship strengthened my confidence and commitment to keep championing women-led climate solutions in my community and beyond.','Mariam Hamza','2025 She Leads Alumni · Ghana','/assets/img/testi/21.svg'],
['I now feel more equipped to engage in community-based climate action and advocate for inclusive, gender-responsive climate policy.','Zainab Kamara','2025 She Leads Alumni · Sierra Leone','/assets/img/testi/22.svg'],
['I am better equipped to be a climate advocate wherever I find myself — not just in title, but in action.','Makaria Dadzie','2025 She Leads Alumni · Ghana','/assets/img/testi/18.svg'],
['The mentorship, sisterhood and shared purpose reminded me that small actions can create lasting impact.','Ethel Eyram Ahorlu','2025 She Leads Alumni · Ghana','/assets/img/testi/20.svg'],
['The programme is valuable for both climate beginners and experienced advocates, especially women learning to use their voices for action.','Mary Kimani','2025 She Leads Alumni · Kenya','/assets/img/testi/17.svg']
];
function Voices(){const cards=[...testimonials,...testimonials];return <section className="voices voicesLive"><div className="voicesHead"><div><span className="voicesKicker">WORDS OF TRANSFORMATION</span><h3>Leadership sounds different when women are given room to own it.</h3></div><div className="voicesMeta"><strong>06</strong><span>voices from the<br/>WOMATE network</span></div></div><div className="voiceViewport"><div className="voiceTrack">{cards.map(([q,n,r,img],i)=><article className="voiceCard" key={i}><div className="voiceCardTop"><img src={img} alt=""/><Quote size={24}/></div><p>{q}</p><div className="voicePerson"><strong>{n}</strong><span>{r}</span></div></article>)}</div></div><div className="voiceHint"><span/> Hover to pause · alumni voices across Africa</div></section>}

function Home(){const[reportOpen,setReportOpen]=useState(false);return <><Hero p={pages['/']} onExplore={()=>setReportOpen(true)}/><main id="content">
<section className="statbar">{stats.map(s=><AnimatedStat key={s.label} {...s}/>)}</section>
<section className="manifesto"><div className="manifestoMark">W</div><div><h3>We don't believe in token inclusion. We believe in full leadership.</h3></div><div><p className="lead">WOMATE equips women with technology, training and community support to move from climate participation to climate leadership.</p><div className="pulseLine"><span/>Community · Storytelling · Capacity building · Advocacy</div></div></section>
<section className="programGrid">{programs.map((p,i)=><Link to={p[2]} className={'program p'+i} key={p[0]}><img className="programArt" src={p[4]}/><div className="programShade"/><div className="programTop"><div className="ico">{p[3]}</div><span>0{i+1}</span></div><div className="programCopy"><h4>{p[0]}</h4><p>{p[1]}</p><ArrowUpRight className="go"/></div></Link>)}</section>
<section className="impactScene"><div className="impactPhoto"><img src="/assets/img/wok-field-collage.png"/><button className="play"><Play fill="currentColor" size={16}/> Field story</button><div className="impactBadge"><Leaf/><span><b>WoK—Action</b>Living climate knowledge</span></div></div><div className="impactCopy"><h3>What women know about land, water and survival should not disappear between generations.</h3><p>WoK—Action creates a living archive of women’s climate knowledge while supporting communities to translate that intelligence into resilience, enterprise and local adaptation.</p><Link to="/wok-action" className="textlink">Enter WoK—Action <MoveRight/></Link></div></section>
<section className="facesRail"><div className="railIntro"><h3>Not beneficiaries.<br/>Climate actors.</h3><p>WOMATE is built around women as researchers, founders, community leaders, storytellers and decision-makers.</p></div><div className="faceCard f1"><img src="/assets/home/climate-leader.png"/><span>LEAD</span></div><div className="faceCard f2"><img src="/assets/home/climate-builder.png"/><span>BUILD</span></div><div className="faceCard f3"><img src="/assets/home/climate-influence.png"/><span>INFLUENCE</span></div><div className="characterCard"><img src="/assets/home/climate-researcher.png"/><span>RESEARCH</span></div></section>
<Voices/>
<Honours/><Partner/></main><ImpactReport open={reportOpen} onClose={()=>setReportOpen(false)}/></>}
function Honours(){return <section className="honours"><div className="honourCopy"><h3>Amplify the Untold.</h3><p>Nominate a woman whose climate leadership is changing a community, field or institution.</p><Link to="/honours" className="pill lime">Nominate a leader <ArrowUpRight/></Link><div className="honourCount">18+ <span>women already documented</span></div></div><div className="honourSymbol"><img src="/assets/hero/honour-symbol.png" alt="WOMATE Climate Honours symbol"/></div></section>}
function Partner(){return <section className="partner"><div><h3>Build climate action that women can lead, trust and sustain.</h3><div className="partnerLine"><Heart/> Research · Programmes · Community · Visibility</div></div><form onSubmit={e=>{e.preventDefault();alert('Thank you. Your enquiry has been captured for the WOMATE team.')}}><input required placeholder="Name"/><input required type="email" placeholder="Work email"/><select><option>Partnership enquiry</option><option>Research</option><option>Programme collaboration</option><option>Funding</option></select><textarea placeholder="What would you like to build together?"/><button className="pill darkbtn">Send enquiry <ArrowUpRight/></button></form></section>}

const details={
she:{items:['Climate foundations','Gender and climate justice','Governance and policy','Advocacy and storytelling','Leadership and community engagement','Climate careers'],title:'Six pillars. One leadership trajectory.',aside:'2026 cohort registration'},
wok:{items:['Indigenous sovereignty','Impact visibility','Economic empowerment','Collective inquiry','Community wealth','Living archives'],title:'Community knowledge, protected and put to work.',aside:'Community-project funding'},
circle:{items:['Membership activation','Member pathways','Community access','Climate Honours access','Peer opportunities','Professional visibility'],title:'A network designed to compound women’s climate agency.',aside:'Registration & payment'},
research:{items:['Climate & gender intelligence','MEL and impact analysis','Evidence support','Community co-creation','Programme design','Knowledge management','Wellbeing & protection','Institutional capacity'],title:'Research made useful, legible and actionable.',aside:'Commission research'},
minds:{items:['Rescue','Restore','Resilience','Peer support pathways','Climate wellbeing research','Guardianship contribution'],title:'The human nervous system belongs in climate strategy.',aside:'Support the programme'},
honours:{items:['The Spotlight','The Circle','The Honour','2025 archive — 18 women','2026 nominations','Journey to October 2026'],title:'Recognition that creates memory, credibility and connection.',aside:'Submit a nomination'},
funding:{items:['Professional application review','Application streamlining','Grant-writing webinar','Technical capacity building','WOMATE community access','Competitive positioning'],title:'From strong idea to stronger application.',aside:'GHS 200 registration'},
volunteer:{items:['Visual Strategist','Digital Systems Lead','Impact Storyteller','Community Impact Lead','Research support','Programme operations'],title:'Bring your professional edge to climate work that matters.',aside:'Apply to volunteer'},
merch:{items:['Signature WOMATE T-shirt','Climate action edition','Circle member edition','Limited programme drops'],title:'The Vault',aside:'Shop WOMATE'},
leadership:{items:['Phillipa Aidoo','Asaa Gyebi-Adjei','Ruby Damenshie-Brown','Hamza Abubakar'],title:'Leadership across climate, technology, research and community.',aside:'Partnership invitation'}};
const pageGallery={she:['/assets/img/team/r.jpg','/assets/img/she.png','/assets/img/cert.svg'],wok:['/assets/img/c.gif','/assets/img/wok/17.svg','/assets/img/wok/20.svg'],circle:['/assets/img/news.png','/assets/img/testi/19.svg','/assets/img/testi/20.svg'],research:['/assets/img/team/pp.jpg','/assets/img/oo.png','/assets/img/featured-img.svg'],minds:['/assets/img/team/asaa.jpeg','/assets/img/news.png','/assets/img/oo1.png'],honours:['/assets/img/CH/NEW.png','/assets/img/CH/c4444.png','/assets/img/CH/c1.png'],leadership:['/assets/img/team/r.jpg','/assets/img/team/asaa.jpeg','/assets/img/team/h.jpg'],funding:['/assets/img/team/pp.jpg','/assets/img/cert.svg','/assets/img/news.png'],volunteer:['/assets/img/news.png','/assets/img/team/r.jpg','/assets/img/team/asaa.jpeg'],merch:['/assets/img/merch/13.png','/assets/img/merch/14.png','/assets/img/merch/12.png']};
const shePillars=[
['01','Climate Change Foundations','Understanding climate change science, causes, and impacts at local, regional, and global levels.'],
['02','Gender & Climate Justice','Examining how climate change affects women and marginalised communities and how equity-centred solutions drive impact.'],
['03','Climate Governance & Policy','Learning how climate institutions, policies, and decision-making spaces function—and how women can engage and lead.'],
['04','Advocacy, Storytelling & Comms','Building skills to communicate climate issues clearly, influence change, and mobilise communities.'],
['05','Leadership & Community Engagement','Strengthening leadership confidence, collaboration, and community-based climate action.'],
['06','Climate Careers & Professional Pathways','Exploring career opportunities, mentorship pathways, and professional growth in climate and sustainability fields.']
];
const SHE_FORM='https://docs.google.com/forms/d/e/1FAIpQLSdwc1l7vlWD4VC6v9cPF_-UdO3VLGDVLRiVJiwmiGE3Aqjs4w/viewform?embedded=true';
function SheLeads(){const[formOpen,setFormOpen]=useState(false);const scrollPillars=()=>document.getElementById('she-pillars')?.scrollIntoView({behavior:'smooth',block:'start'});useEffect(()=>{if(!formOpen)return;const onKey=e=>e.key==='Escape'&&setFormOpen(false);window.addEventListener('keydown',onKey);document.body.style.overflow='hidden';return()=>{window.removeEventListener('keydown',onKey);document.body.style.overflow=''}},[formOpen]);return <>
<section className="hero hero-she sheHero"><div className="heroTop"><div className="heroCopy"><h1>She Leads Climate Mentorship.</h1><div className="actions"><button className="pill lime" onClick={()=>setFormOpen(true)}>Join next cohort <ArrowUpRight size={16}/></button><button className="pill ghost" onClick={scrollPillars}>Explore <ChevronDown size={17}/></button></div></div><HeroVisual type="she"/></div></section>
<main id="content" className="shePage">
<section className="sheIntro"><div className="sheIntroMark">SHE<br/>LEADS</div><div><h2>Where young women gain the knowledge, skills and courage to lead climate action.</h2></div><p>Climate leadership is not a title. It is the ability to understand the system, find your voice, build with others and enter decision-making spaces prepared.</p></section>
<section id="she-pillars" className="shePillars"><header><span>THE LEARNING ARCHITECTURE</span><h2>Six Core Learning Pillars</h2><p>Equipping young women with knowledge, skills and pathways for climate leadership.</p></header><div className="shePillarGrid">{shePillars.map(([n,t,d])=><article key={n}><div className="pillarTop"><span>{n}</span><Leaf size={20}/></div><h3>{t}</h3><p>{d}</p><div className="pillarLine"/></article>)}</div></section>
<section className="shePrestige"><div className="prestigeCopy"><span>THE 2026 SEAL OF EXCELLENCE</span><h2>The Prestige Awaits You.</h2><p>A digital credential validating rounded climate leadership—not passive attendance. Learning, practice, community contribution and a visible next step.</p><div className="prestigeProof"><ShieldCheck size={18}/> Credential · leadership evidence · professional signal</div></div><div className="prestigeCert"><img src="/assets/img/she-leads-certificate-reveal.png" alt="She Leads 2026 Certificate of Participation"/></div></section>
<section className="sheFellows"><div><span>THE COMMUNITY AFTER THE CLASSROOM</span><h2>The cohort becomes a network.</h2><p>Women leave with more than climate knowledge: they leave with peers across African countries, shared language for leadership, and a community that continues beyond the programme.</p><button className="pill darkbtn" onClick={()=>setFormOpen(true)}>Join next cohort <ArrowUpRight size={16}/></button></div><figure><img src="/assets/img/she.png" alt="She Leads Climate outstanding fellows"/></figure></section>
<Partner/>
</main>
{formOpen&&<div className="formModal" role="dialog" aria-modal="true" aria-label="Join the next She Leads cohort"><button className="formBackdrop" aria-label="Close form" onClick={()=>setFormOpen(false)}/><div className="formPanel"><div className="formPanelHead"><div><span>SHE LEADS · NEXT COHORT</span><strong>Join the next cohort</strong></div><button onClick={()=>setFormOpen(false)} aria-label="Close"><X size={22}/></button></div><iframe src={SHE_FORM} title="She Leads cohort interest form" loading="lazy">Loading…</iframe></div></div>}
</>}


const wokPillars=[
['01','DOCUMENTATION','Indigenous Sovereignty','Preserving women’s local and indigenous knowledge systems, traditions, and climate adaptation practices before they are lost.'],
['02','ANALYSIS','Impact Visibility','Examining how climate change reshapes women’s livelihoods, health, and everyday wellbeing across communities.'],
['03','RESILIENCE','Economic Alchemy','Identifying practical skills, trades, and income pathways that strengthen women’s economic and climate resilience.'],
['04','PARTICIPATION','Collective Inquiry','Using participatory research, focus groups, and interviews so women co-lead knowledge creation and decision-making.'],
['05','MOBILIZATION','Community Wealth','Mobilising resources collaboratively to support women-led solutions, skills training, and local adaptation initiatives.'],
['06','STORYTELLING','Living Archives','Documenting insights through storytelling, reports, and shared learning to elevate women’s voices in climate discourse.']
];
const WOK_FUND='https://paystack.shop/pay/wok-action-project-funds';
function WokAction(){const goPillars=()=>document.getElementById('wok-pillars')?.scrollIntoView({behavior:'smooth',block:'start'});return <>
<section className="hero hero-wok wokHeroClassic"><div className="heroTop"><div className="heroCopy"><h1>WOK. Action</h1><div className="actions"><a className="pill lime" href={WOK_FUND} target="_blank" rel="noreferrer">Fund Community Project</a><button className="pill ghost" onClick={goPillars}>Explore Research</button></div></div><HeroVisual type="wok"/></div></section>
<main className="wokPage">
<section className="wokTheme"><div className="wokThemeMeta"><span>2025 ACTIVE THEME</span><strong>WOMATE · COMMUNITY RESEARCH</strong></div><div><h2>“Rising Together: How Women’s Local Wisdom and Everyday Leadership Shape Adaptation.”</h2><p>Bridging the gap between lived experience and practical solutions through a documented storytelling approach.</p></div></section>
<section id="wok-pillars" className="wokPillars"><div className="wokSectionHead"><span>THE ACTION PILLARS</span><h2>Knowledge becomes infrastructure when communities can use it.</h2></div><div className="wokPillarGrid">{wokPillars.map(([n,k,t,d])=><article key={n}><div className="wokPillarTop"><span>{n}</span><small>{k}</small></div><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="wokEvidence"><div className="wokEvidenceLead"><span>FIELD DOCUMENTATION</span><h2>Research with women. Not research about women.</h2><p>WoK—Action treats communities as knowledge holders and co-creators. Interviews, focus groups, observation and storytelling are used to document adaptation practices while keeping women visible in the evidence.</p></div><figure className="wokCollage"><img src="/assets/img/wok/19.svg" alt="WoK-Action community field documentation"/><figcaption>Community documentation · Okere District</figcaption></figure><div className="wokEvidenceTiles"><figure><img src="/assets/img/wok/17.svg"/><span>LOCAL KNOWLEDGE</span></figure><figure><img src="/assets/img/wok/20.svg"/><span>PARTICIPATORY RESEARCH</span></figure></div></section>
<section className="wokProof"><div><b>2025</b><span>Launch year</span></div><div><b>Okere</b><span>Active district</span></div><div><b>100%</b><span>Community led</span></div><blockquote>“To care about climate change, you only need to be one thing — a person living on planet Earth who wants a better future.”<cite>Katharine Hayhoe · Climate scientist & author</cite></blockquote></section>
<section className="wokFund"><div><span>FUEL THE FUTURE</span><h2>Fund women-led knowledge, research and practical adaptation.</h2><p>Your investment directly supports the expansion of WoK—Action research, documentation and skills training.</p></div><a href={WOK_FUND} target="_blank" rel="noreferrer" className="pill lime">Open funding portal <ArrowUpRight size={17}/></a></section>
<Partner/>
</main></>}



const CIRCLE_FORM=import.meta.env.VITE_CIRCLE_FORM_EMBED_URL||'https://docs.google.com/forms/d/e/1FAIpQLSf-qz5my6XYer4uxyarq9Ot4UQxOvrTglGus26kX9r_D2SgRQ/viewform?embedded=true';
const CIRCLE_PAYMENT=import.meta.env.VITE_CIRCLE_PAYMENT_URL||'https://paystack.shop/pay/womate-circle-fees';
const CIRCLE_WHATSAPP=import.meta.env.VITE_CIRCLE_WHATSAPP_URL||'';
const CIRCLE_INQUIRY=import.meta.env.VITE_CIRCLE_INQUIRY_ENDPOINT||'';
const circleTiers=[
['01','The Collective','Free / Lifetime',['Basic opportunity sharing — jobs & grants','Community training exchanges','Regular volunteering openings','Digital resource library access']],
['02','The Practitioner','GHS 500 / Annual',['Priority involvement in WOMATE projects','Invitations to private sitting programmes','Advanced capacity-building sessions','Verified speaking opportunities']],
['03','The Vanguard','GHS 1,000 / Annual',['VIP access to Climate Honours convening','Private funding & grant matchmaking','Executive speaking placements','Strategic leadership mentorship','Permanent seat in the Advisory Sit']]
];
function CirclePage(){
 const[activation,setActivation]=useState(false),[tier,setTier]=useState('The Collective'),[sent,setSent]=useState(false),[sending,setSending]=useState(false);
 const goPath=()=>document.getElementById('circle-pathways')?.scrollIntoView({behavior:'smooth',block:'start'});
 const openJoin=(name='The Collective')=>{setTier(name);setActivation(true)};
 const openWhatsApp=()=>{if(CIRCLE_WHATSAPP)window.open(CIRCLE_WHATSAPP,'_blank','noopener,noreferrer');else alert('Add VITE_CIRCLE_WHATSAPP_URL to your .env to activate the WOMATE Circle WhatsApp route.');};
 async function sendInquiry(e){e.preventDefault();const form=e.currentTarget;setSending(true);try{if(!CIRCLE_INQUIRY)throw new Error('missing');const data=Object.fromEntries(new FormData(form));const r=await fetch(CIRCLE_INQUIRY,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error('request');setSent(true);form.reset()}catch(err){if(err.message==='missing') alert('Add VITE_CIRCLE_INQUIRY_ENDPOINT to your .env to activate direct inquiry delivery.');else alert('Your inquiry could not be sent. Please try again.')}finally{setSending(false)}}
 return <>
<section className="hero hero-circle"><div className="heroTop"><div className="heroCopy"><h1>A climate community for women.</h1><div className="actions"><button className="pill lime" onClick={()=>openJoin()}>Enter the Circle <ArrowUpRight size={16}/></button><button className="pill ghost" onClick={goPath}>Explore membership</button></div></div><HeroVisual type="circle"/></div></section>
<main className="circlePage">
<section className="circleIntro"><span>THE INNER RING OF CLIMATE LEADERSHIP</span><div><h2>Influence grows faster when women do not have to build alone.</h2><p>The WOMATE Circle is a specialised ecosystem for women architects of sustainability: a place to exchange intelligence, access opportunity, build professional visibility and turn peer connection into collective power.</p></div></section>
<section className="circlePromise"><div className="circleSectionHead"><span>FOSTERING VISIBILITY</span><h2>More than a network. A growth accelerator.</h2></div><div className="circlePromiseGrid"><article><b>01 · SHARED LEARNING</b><h3>Stay current together.</h3><p>Weekly capacity-building exchanges, resource sharing and peer intelligence for women navigating climate and sustainability work.</p></article><article><b>02 · DIRECT ACCESS</b><h3>See opportunity sooner.</h3><p>Curated fellowships, grants, projects and international speaking opportunities selected for women building credible climate careers.</p></article><article><b>03 · THE ANNUAL SIT</b><h3>Lead with intention.</h3><p>A strategic reflection and goal-setting space to review progress, sharpen direction and enter the next year deliberately.</p></article></div></section>
<section id="circle-pathways" className="circlePathways"><div className="circleSectionHead"><span>MEMBER PATHWAYS</span><h2>Choose the level of access that matches where you are going.</h2></div><div className="circleTierGrid">{circleTiers.map(([n,t,price,items],i)=><article className={'circleTier '+(i===1?'featured':'')} key={n}><div className="circleTierTop"><span>{n}</span><b>{i===0?'OPEN ACCESS':i===1?'PROFESSIONAL':'EXECUTIVE'}</b></div><h3>{t}</h3><div className="circlePrice">{price}</div><ul>{items.map(x=><li key={x}>{x}</li>)}</ul><button className={i===1?'pill darkbtn':'pill lime'} onClick={()=>openJoin(t)}>{i===0?'Join community':i===1?'Activate membership':'Enter the Vanguard'}</button></article>)}</div></section>
<section className="circlePath"><div className="circlePathCopy"><span>MEMBERSHIP ACTIVATION</span><h2>One clear route into the Circle.</h2><p>Complete your credentials first. Free members continue to community onboarding; Practitioner and Vanguard members complete the annual membership payment before WhatsApp admission.</p></div><div className="circleSteps"><div><b>01</b><strong>Complete credentials</strong><p>Tell WOMATE who you are, where you work and the climate space you are building in.</p></div><div><b>02</b><strong>Select your pathway</strong><p>Choose Collective, Practitioner or Vanguard based on the access you need.</p></div><div><b>03</b><strong>Secure membership</strong><p>Practitioner and Vanguard members complete annual payment through the configured secure payment route.</p></div><div><b>04</b><strong>Enter WhatsApp</strong><p>Continue to the Circle WhatsApp community for onboarding, opportunities, learning and peer connection.</p></div></div></section>
<section className="circleAccess"><div className="circleAccessCopy"><span>COMMUNITY ACCESS</span><h2>Already registered?</h2><p>Use the direct community route after completing your membership credentials and, where applicable, annual payment.</p></div><div className="circleAccessActions"><button className="pill lime" onClick={openWhatsApp}>Open WhatsApp community <ArrowUpRight size={16}/></button><a className="pill ghost" href={CIRCLE_PAYMENT} target="_blank" rel="noreferrer">Secure annual membership <ArrowUpRight size={16}/></a></div></section>
<section className="circleInquiry"><div><span>ASK WOMATE</span><h2>Not sure which pathway fits?</h2><p>Send a short note and the WOMATE team can guide you to the right Circle membership route.</p></div>{sent?<div className="circleSuccess"><ShieldCheck size={30}/><strong>Inquiry received.</strong><p>WOMATE can now follow up using the contact details you provided.</p></div>:<form onSubmit={sendInquiry}><input name="name" required placeholder="Full name"/><input name="email" required type="email" placeholder="Email address"/><input name="country" placeholder="Country"/><select name="pathway" defaultValue="Not sure"><option>Not sure</option><option>The Collective</option><option>The Practitioner</option><option>The Vanguard</option></select><textarea name="message" required placeholder="Tell us what you are looking for from the Circle."/><button className="pill darkbtn" disabled={sending}>{sending?'Sending…':'Send inquiry'} <ArrowUpRight size={16}/></button></form>}</section>
</main>
{activation&&<div className="circleModal" role="dialog" aria-modal="true"><button className="circleModalBackdrop" aria-label="Close membership activation" onClick={()=>setActivation(false)}/><div className="circleModalPanel"><div className="circleModalHead"><div><span>MEMBERSHIP ACTIVATION</span><h2>{tier}</h2></div><button aria-label="Close" onClick={()=>setActivation(false)}><X/></button></div><div className="circleModalBody"><div className="circleFormFrame"><iframe title="WOMATE Circle membership form" src={CIRCLE_FORM}>Loading…</iframe></div><aside><span>AFTER SUBMITTING</span><h3>Complete your route.</h3><p>{tier==='The Collective'?'The Collective is free. Submit your credentials, then continue directly to the community.':'Submit your credentials, complete annual membership payment, then continue to the WhatsApp community for onboarding.'}</p>{tier!=='The Collective'&&<a href={CIRCLE_PAYMENT} target="_blank" rel="noreferrer" className="pill lime">Proceed to secure payment <ArrowUpRight size={16}/></a>}<button onClick={openWhatsApp} className="pill darkbtn">{tier==='The Collective'?'Proceed to WhatsApp group':'Done & join community'} <ArrowUpRight size={16}/></button><small>Paid members should retain proof of successful payment for onboarding verification.</small></aside></div></div></div>}
</>}

const researchServices=[
['01','RESEARCH & POLICY','Climate & Gender Intel','Gender-responsive research informing policy and community action. Vulnerability assessments, resilience studies, and indigenous knowledge documentation.',['Vulnerability Mapping','Policy Briefs','Stakeholder Consultation']],
['02','MEASUREMENT','MEL & Impact Analysis','Measuring results and strengthening accountability through comprehensive Monitoring, Evaluation, and Learning frameworks.',['Impact Frameworks','SDG Integration','Adaptive Management']],
['03','DATA SCIENCE','Evidence Support','Translating complex quantitative and qualitative data into actionable dashboards and visualizations for strategic planning.',['Data Dashboards','Economic Analysis','Synthesis Reports']],
['04','PARTICIPATORY','Community Co-Creation','Participatory approaches that centre women and youth as co-creators of climate solutions and ownership.',['Needs Assessment','Youth Mapping','Participatory Action']],
['05','OPERATIONS','Programme Design','Support across the full project cycle: Theory of Change, implementation, grant management, donor reporting, and risk management.',['Theory of Change','Implementation','Grant Management']],
['06','ADVOCACY','Knowledge Management','Amplifying women’s voices through strategic communications and digital platforms that strengthen visibility and influence.',['Advocacy Campaigns','Learning Products','Multimedia Content']],
['07','SPECIALIZED','Wellbeing & Protection','Research at the intersection of climate impacts, psychosocial mental health, and gender-based social protection.',['Psychosocial Design','Outreach Support','Stigma Reduction']],
['08','TRAINING','Institutional Capacity','Bespoke workshops and mentorship design for organisations strengthening climate and gender leadership.',['Curriculum Design','Leadership Mentorship','Digital Literacy']]
];
function ResearchPage(){const goInquiry=()=>document.getElementById('research-inquiry')?.scrollIntoView({behavior:'smooth',block:'start'});return <>
<section className="hero hero-research"><div className="heroTop"><div className="heroCopy"><h1>We Research. You Lead.</h1><div className="actions"><button className="pill lime" onClick={goInquiry}>Inquire <ArrowUpRight size={16}/></button></div></div><HeroVisual type="research"/></div></section>
<main className="researchPage">
<section className="researchIntro"><div className="researchIntroLabel">STRATEGIC INSIGHT & RESEARCH</div><div><h2>Evidence that can survive the boardroom and still make sense on the ground.</h2><p>WOMATE provides organisations and donors with the analytical depth to design, implement and assess gender-responsive climate initiatives across African contexts.</p></div></section>
<section className="researchServices"><div className="researchSectionHead"><span>WHAT WE DO</span><h2>From climate intelligence to institutional capacity.</h2></div><div className="researchServiceGrid">{researchServices.map(([n,k,t,d,tags])=><article key={n}><div className="researchServiceTop"><span>{n}</span><small>{k}</small></div><h3>{t}</h3><p>{d}</p><div className="researchTags">{tags.map(x=><span key={x}>{x}</span>)}</div></article>)}</div></section>
<section className="researchBridge"><div><span>HOW WOMATE WORKS</span><h2>Lived experience in. Decision-grade evidence out.</h2></div><div className="researchBridgeSteps"><div><b>01</b><strong>Listen</strong><p>Start with communities, context and the questions decision-makers actually need answered.</p></div><div><b>02</b><strong>Analyse</strong><p>Combine qualitative insight, quantitative evidence and gender-responsive interpretation.</p></div><div><b>03</b><strong>Translate</strong><p>Turn findings into useful briefs, frameworks, dashboards, learning products and programme decisions.</p></div></div></section>
<section className="researchVisual"><figure><img src="/assets/hero/research.png" alt="WOMATE climate researcher"/></figure><div><span>RESEARCH THAT MOVES</span><h2>Not research for the shelf.</h2><p>Our work is designed to strengthen programmes, shape policy conversations, improve accountability and make women’s lived climate realities harder to ignore.</p><div className="researchSignals"><span>Gender-responsive</span><span>Participatory</span><span>Evidence-led</span><span>Actionable</span></div></div></section>
<section id="research-inquiry" className="researchInquiry"><div className="researchInquiryCopy"><span>BRIDGE THE GAP</span><h2>Integrate lived experience with policy relevance.</h2><p>Tell us what you are designing, evaluating, researching or trying to understand. WOMATE will review the brief and follow up on the right research or strategic consultation pathway.</p></div><form onSubmit={e=>{e.preventDefault();alert('Thank you. Your research inquiry has been captured for the WOMATE team.')}}><label>Full name<input required placeholder="Name Surname"/></label><label>Professional email<input required type="email" placeholder="email@domain.com"/></label><label>Organisation<input placeholder="Organisation / institution"/></label><label>How can we collaborate?<textarea required placeholder="Tell us about the research, programme, evaluation or evidence need."/></label><button className="pill lime">Send inquiry <ArrowUpRight size={16}/></button></form></section>
</main></>}


const HEAL_PAYMENT_BASE=import.meta.env.VITE_HEAL_PAYMENT_URL||'';
const HEAL_GUARDIAN_FORM=import.meta.env.VITE_HEAL_GUARDIAN_FORM_EMBED_URL||'';
const HEAL_INQUIRY_ENDPOINT=import.meta.env.VITE_HEAL_INQUIRY_ENDPOINT||'';
const healTiers=[
  {id:'seed',name:'The Seed',price:'GHS 300',desc:'Covers emergency medical care and psychiatric stabilisation for one week.',focus:'Immediate care'},
  {id:'root',name:'The Root',price:'GHS 600',desc:'Funds a full month of vocational training and nutritional support for a resident.',focus:'Recovery & skills'},
  {id:'canopy',name:'The Canopy',price:'GHS 1,000',desc:'Sustains a safe-house room with 24/7 security and specialist care.',focus:'Safe sanctuary'}
];
function ResilientMinds(){
 const investRef=useRef(null);const[guardianOpen,setGuardianOpen]=useState(false);const[selected,setSelected]=useState('');const[status,setStatus]=useState('');
 const goGuardians=()=>investRef.current?.scrollIntoView({behavior:'smooth',block:'start'});
 const contribute=(tier)=>{setSelected(tier.id);if(HEAL_PAYMENT_BASE){const sep=HEAL_PAYMENT_BASE.includes('?')?'&':'?';window.open(`${HEAL_PAYMENT_BASE}${sep}tier=${encodeURIComponent(tier.id)}&amount=${tier.price.replace(/\D/g,'')}`,'_blank','noopener,noreferrer')}else setGuardianOpen(true)};
 const submitInquiry=async(e)=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setStatus('sending');try{if(!HEAL_INQUIRY_ENDPOINT){setStatus('ready');return}const r=await fetch(HEAL_INQUIRY_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,source:'Resilient Minds'})});if(!r.ok)throw new Error();setStatus('sent');e.currentTarget.reset()}catch{setStatus('error')}};
 const [guardianStatus,setGuardianStatus]=useState('');
 const submitGuardian=async(e)=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));setGuardianStatus('sending');try{if(!HEAL_INQUIRY_ENDPOINT)throw new Error('endpoint');const r=await fetch(HEAL_INQUIRY_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({...data,source:'Resilient Minds Guardian',pathway:selected||'guardian'})});if(!r.ok)throw new Error();setGuardianStatus('sent');form.reset()}catch{setGuardianStatus('error')}};

 return <>
  <section className="hero hero-minds"><div className="heroTop"><div className="heroCopy"><h1>To See What Is Hidden.</h1><div className="actions"><button className="pill lime" onClick={goGuardians}>BECOME A GUARDIAN</button></div></div><HeroVisual type="minds"/></div></section>
  <main className="healPage">
   <section className="healIntro"><span>RESILIENT MINDS · RESILIENT WOMEN</span><div><h2>Climate justice must make room for the mind.</h2><p>Climate shocks, displacement, poverty and social exclusion can compound mental-health distress for women already living in vulnerable conditions. Resilient Minds is WOMATE’s restoration initiative for young women who need more than awareness: medical care, safety, psychosocial support, skills and a credible route back to dignity.</p></div></section>
   <section className="healPath"><div className="healSectionHead"><span>THE RESTORATION PATH</span><h2>Rescue. Restore. Resilience.</h2></div><div className="healPathGrid">
    <article><b>01</b><div className="healIcon"><Heart size={26}/></div><h3>Rescue</h3><p>Identifying and compassionately moving young women from isolation and street vulnerability into a safer environment for immediate support.</p></article>
    <article><b>02</b><div className="healIcon"><Brain size={26}/></div><h3>Restore</h3><p>Professional psychiatric assessment, clinical care, psychosocial support, nutrition and structured recovery that rebuild the foundations of self.</p></article>
    <article><b>03</b><div className="healIcon"><Leaf size={26}/></div><h3>Resilience</h3><p>Vocational pathways—from tailoring to catering and other practical arts—supporting independence, agency and a future beyond survival.</p></article>
   </div></section>
   <section className="healWhy"><div className="healWhyVisual"><img src="/assets/hero/resilient-minds.png" alt="Resilient Minds — women, care and climate resilience"/></div><div className="healWhyCopy"><span>THE OVERLOOKED INTERSECTION</span><h2>Environmental crisis can become a mental-health crisis.</h2><p>When homes, incomes, food systems and community ties are disrupted, the psychological cost can be profound. WOMATE treats care as part of resilience—not as an afterthought.</p><div className="healSignals"><span>Medical care</span><span>Safe accommodation</span><span>Psychosocial support</span><span>Vocational skills</span></div></div></section>
   <section className="healGuardians" ref={investRef}><div className="healSectionHead"><span>INVEST IN RESTORATION</span><h2>Choose a tier of guardianship.</h2></div><p className="healGuardianLead">Each contribution sustains a different layer of the sanctuary—from urgent stabilisation to long-term recovery and safety.</p><div className="healTierGrid">{healTiers.map((t,i)=><article className={'healTier '+(i===1?'featured':'')} key={t.id}><div className="healTierTop"><span>{String(i+1).padStart(2,'0')}</span><b>{t.focus}</b></div><h3>{t.name}</h3><strong className="healPrice">{t.price}</strong><p>{t.desc}</p><button className="pill darkbtn" onClick={()=>contribute(t)}>Contribute</button></article>)}</div></section>
   <section className="healGuardianStory"><div><span>GUARDIANSHIP</span><h2>Support that stays long enough to matter.</h2></div><div><p>A Guardian does more than fund a moment. Guardians help WOMATE create continuity across rescue, clinical restoration, safe living and skills-building.</p><button className="pill lime" onClick={()=>{setSelected('guardian');setGuardianOpen(true)}}>Become a Guardian</button></div></section>
   <section className="healInquiry"><div><span>PARTNER IN CARE</span><h2>Institutional, clinical or programme partnership?</h2><p>Use this route for hospitals, clinicians, safe-house partners, vocational trainers, donors and organisations interested in supporting the initiative.</p></div><form onSubmit={submitInquiry}><input name="name" required placeholder="Full name"/><input name="email" required type="email" placeholder="Professional email"/><input name="organisation" placeholder="Organisation"/><textarea name="message" required placeholder="How would you like to support Resilient Minds?"/><button className="pill darkbtn" disabled={status==='sending'}>{status==='sending'?'Sending…':'Send inquiry'}</button>{status==='sent'&&<small>Thank you. Your inquiry has been received.</small>}{status==='ready'&&<small>Add VITE_HEAL_INQUIRY_ENDPOINT in .env to connect submissions.</small>}{status==='error'&&<small>Submission failed. Please try again.</small>}</form></section>
  </main>
  {guardianOpen&&<div className="healModal" role="dialog" aria-modal="true"><button className="healModalBackdrop" onClick={()=>setGuardianOpen(false)} aria-label="Close"/><div className="healModalPanel"><div className="healModalHead"><div><span>RESILIENT MINDS</span><h2>Become a Guardian</h2></div><button onClick={()=>setGuardianOpen(false)}><X/></button></div><div className="healModalBody"><form className="healNativeGuardian" onSubmit={submitGuardian}><div className="guardianFormIntro"><Heart size={30}/><div><h3>Stand with Resilient Minds.</h3><p>Register your interest in becoming a Guardian. WOMATE will follow up using the details you provide.</p></div></div><input name="name" required placeholder="Full name"/><input name="email" required type="email" placeholder="Email address"/><input name="phone" required placeholder="Phone / WhatsApp number"/><input name="country" required placeholder="Country"/><select name="guardian_level" defaultValue={selected||'guardian'}><option value="guardian">Guardian · general interest</option><option value="seed">The Seed · GHS 300</option><option value="root">The Root · GHS 600</option><option value="canopy">The Canopy · GHS 1,000</option></select><textarea name="message" placeholder="Anything WOMATE should know?"/><label className="guardianConsent"><input type="checkbox" required/> I agree to be contacted by WOMATE about Resilient Minds guardianship.</label><button className="pill darkbtn" disabled={guardianStatus==='sending'}>{guardianStatus==='sending'?'Submitting…':'Register as a Guardian'}</button>{guardianStatus==='sent'&&<div className="guardianSuccess"><b>Interest received.</b><span>Thank you. WOMATE will contact you about the next guardianship step.</span></div>}{guardianStatus==='error'&&<small className="guardianError">We could not submit the form. Please try again.</small>}</form></div></div></div>}
 </>
}

const HONOURS_FORM=import.meta.env.VITE_HONOURS_NOMINATION_FORM_URL||'https://form.jotform.com/260154019157048';
const honoursArchiveByYear={
  2025:['c6.png','c4444.png','36.png','c44.png','ch3.jpg','c3.png','c5.png','c10.png','CHJ.png','ch1.jpg','ch2.jpg','CC.png','c12.png','c9.png','c2.png','c1.png','66.jpg','NEW.png'],
  2026:[]
};
const honoursYears=[2025,2026];
function HonoursPage(){
 const [archiveYear,setArchiveYear]=useState(2025);
 const[formOpen,setFormOpen]=useState(false);
 const archiveRef=useRef(null);
 const openForm=()=>setFormOpen(true);
 const goArchive=()=>archiveRef.current?.scrollIntoView({behavior:'smooth',block:'start'});
 return <>
  <section className="hero hero-honours"><div className="heroTop"><div className="heroCopy"><h1>Amplify the Untold.</h1><div className="actions"><button className="pill lime" onClick={openForm}>NOMINATE A LEADER</button><Link to="/circle" className="pill ghost">Join the community</Link></div></div><HeroVisual type="honours"/></div></section>
  <main className="honoursPage">
   <section className="honoursIntro"><span>CLIMATE HONOURS · 2026</span><div><h2>African women are not just witnessing climate change. They are rewriting its ending.</h2><p>Following the legacy of 18 featured pioneers in 2025, WOMATE is documenting the next generation of women whose leadership is changing communities, fields and institutions across Africa.</p></div><aside><b>18</b><span>Voices elevated in 2025</span><button onClick={goArchive}>View the archive</button></aside></section>
   <section className="honoursJourney"><div className="honoursSectionHead"><span>THE JOURNEY TO OCTOBER 2026</span><h2>Recognition designed to create momentum, not a moment.</h2><p>Featured changemakers move into a wider WOMATE ecosystem built around visibility, community and long-term leadership opportunity.</p></div><div className="honoursJourneyGrid"><article><b>01</b><h3>Nomination</h3><p>Name a woman whose climate work deserves wider recognition—or submit your own story.</p></article><article><b>02</b><h3>Editorial review</h3><p>WOMATE reviews each story for clarity, credibility, impact and relevance to women-led climate action.</p></article><article><b>03</b><h3>Spotlight</h3><p>Selected leaders are documented through WOMATE’s Digital Magazine and Global Spotlight storytelling.</p></article><article><b>04</b><h3>October 2026</h3><p>The next cohort of climate leaders is elevated into the Honours ecosystem and connected to future opportunities.</p></article></div></section>
   <section className="honoursArchive" ref={archiveRef}><div className="honoursArchiveSymbol" aria-hidden="true"><img src="/assets/hero/honour-symbol.png" alt=""/></div><div className="honoursArchiveHead"><div><span>CLIMATE HONOURS ARCHIVE</span><h2>{archiveYear===2025?'18 pioneers. One growing record of African climate leadership.':archiveYear+' Climate Honours'}</h2></div><p>The archive is not decoration. It is institutional memory—evidence that women’s climate work is happening, scaling and shaping the continent.</p></div><div className="honoursYearTabs" role="tablist" aria-label="Climate Honours archive years">{honoursYears.map(y=><button key={y} role="tab" aria-selected={archiveYear===y} className={archiveYear===y?'active':''} onClick={()=>setArchiveYear(y)}>{y}{y===2026&&<small>Unveiling Nov–Dec</small>}</button>)}</div>{archiveYear===2025?<div className="honoursArchiveGrid">{honoursArchiveByYear[2025].map((im,i)=><figure key={im}><img src={'/assets/img/CH/'+im} alt={'WOMATE Climate Honours 2025 pioneer '+(i+1)} loading="lazy"/><figcaption><span>{String(i+1).padStart(2,'0')}</span><b>2025 Climate Honours</b></figcaption></figure>)}</div>:<div className="honoursLockedYear"><span>2026</span><h3>The next record is being prepared.</h3><p>WOMATE will unveil the 2026 Climate Honours cohort in November–December 2026. The archive will open here when the cohort is announced.</p><button className="pill lime" onClick={openForm}>NOMINATE A LEADER</button></div>}</section>
   <section className="honoursPathways"><div className="honoursSectionHead"><span>IS THE STORY YOURS TO TELL?</span><h2>Visibility is only the first layer.</h2><p>Whether it is your own innovation or a woman leading in your community, WOMATE turns recognition into access.</p></div><div className="honoursPathwayGrid"><article><span>01</span><h3>The Spotlight</h3><p>Be featured in WOMATE’s upcoming Digital Magazine and Global Spotlight series.</p></article><article><span>02</span><h3>The Circle</h3><p>Receive one-year access to the WOMATE membership community for networking and collaboration.</p></article><article><span>03</span><h3>The Honor</h3><p>Gain a direct nomination pathway toward the WOMATE Global Awards in 2029.</p></article></div></section>
   <section className="honoursBenefits"><div><span>MEMBERSHIP BENEFITS</span><h2>A 360° ecosystem around recognised leaders.</h2></div><div className="honoursBenefitList"><p>Exclusive platform for cross-continental networking</p><p>Priority invitations to 2026 climate summits and workshops</p><p>Early access to volunteer roles and technological project collaborations</p><p>Strategic visibility across WOMATE’s 360° ecosystem</p></div></section>
   <section className="honoursNominate"><div><span>AMPLIFY THE UNTOLD</span><h2>Know a woman rewriting Africa’s climate future?</h2><p>Nominate her—or submit your own climate leadership story—for consideration in the 2026 Climate Honours.</p></div><button className="pill lime" onClick={openForm}>NOMINATE A LEADER</button></section>
   <Partner/>
  </main>
  {formOpen&&<div className="honoursModal" role="dialog" aria-modal="true"><button className="honoursModalBackdrop" onClick={()=>setFormOpen(false)} aria-label="Close nomination form"/><div className="honoursModalPanel"><div className="honoursModalHead"><div><span>WOMATE CLIMATE HONOURS</span><h2>Nominate a leader</h2></div><button onClick={()=>setFormOpen(false)} aria-label="Close"><X/></button></div><iframe src={HONOURS_FORM} title="African Women in Climate Change Story Submission">Loading…</iframe></div></div>}
 </>
}


function LeadershipPage(){
 const team=[
  {name:'Phillipa Aidoo',role:'Chief Executive Officer',unit:'TECHNOLOGY',image:'/assets/img/team/phillipa-aidoo.png',linkedin:'https://gh.linkedin.com/in/phillipa-aidoo',bio:"Chief Strategist & Full-stack Developer. Architect of WOMATE’s integrated climate-tech ecosystem and the organisation’s strategic direction."},
  {name:'Asaa Gyebi-Adjei',role:'Board Member',unit:'RESEARCH',image:'/assets/img/team/asaa.jpeg',linkedin:'https://gh.linkedin.com/in/asaa-gyebi-adjei-902a03111',bio:'PhD Candidate & Strategic Economist. Leads data analysis and research thinking for high-impact adaptation projects.'},
  {name:'Ruby Damenshie-Brown',role:'Chief Operating Officer',unit:'PROGRAMS',image:'/assets/img/team/ruby-damenshie-brown.jpg',linkedin:'https://gh.linkedin.com/in/ruby-damenshie-brown-she-her-582b7287',bio:'Operations Specialist focused on community engagement, programme delivery and the regional scaling of climate initiatives.'},
  {name:'Hamza Abubakar',role:'Chief Communications Officer',unit:'ADVOCACY',image:'/assets/img/team/h.jpg',linkedin:'https://gh.linkedin.com/in/hamza-abubakar-537852214',bio:'UN Climate Champion advancing global communication, advocacy and public engagement for planetary stewardship.'}
 ];
 const [status,setStatus]=useState('');
 const endpoint=import.meta.env.VITE_LEADERSHIP_INQUIRY_ENDPOINT||'';
 const submit=async e=>{e.preventDefault();setStatus('sending');const f=new FormData(e.currentTarget);const payload=Object.fromEntries(f.entries());try{if(endpoint){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('Request failed');setStatus('sent');e.currentTarget.reset()}else{const subject=encodeURIComponent('WOMATE leadership partnership enquiry');const body=encodeURIComponent(`Name / Organisation: ${payload.name}\nEmail: ${payload.email}\nInterest: ${payload.interest}\n\n${payload.message||''}`);window.location.href=`mailto:womatead@gmail.com?subject=${subject}&body=${body}`;setStatus('sent')}}catch(err){setStatus('error')}};
 const goTeam=()=>document.getElementById('leadership-team')?.scrollIntoView({behavior:'smooth'});
 const goPartner=()=>document.getElementById('leadership-partner')?.scrollIntoView({behavior:'smooth'});
 return <><section className="hero hero-leadership"><div className="heroTop"><div className="heroCopy"><h1>Driving Inclusive Climate Action with Technology.</h1><div className="actions"><button className="pill lime" onClick={goTeam}>Meet the leadership</button><button className="pill ghost" onClick={goPartner}>Partner with WOMATE</button></div></div><HeroVisual type="leadership"/></div></section><main id="content" className="leadershipPage">
  <section className="leadershipMandate"><div><span>STRATEGIC OVERSIGHT · 2026</span><h2>Leadership built to connect community wisdom with scalable climate systems.</h2></div><div><p>WOMATE drives women-led climate adaptation across Africa by connecting technology, research, programmes and advocacy into one operating ecosystem.</p><p>That means leadership is not ceremonial. Each executive discipline is tied directly to how knowledge is created, programmes are delivered, communities are represented and climate action is scaled.</p></div></section>
  <section className="leadershipTeam" id="leadership-team"><div className="leadershipSectionHead"><span>EXECUTIVE UNIT</span><h2>Four disciplines. One climate mandate.</h2><p>The leadership team combines technical building, research intelligence, programme operations and public advocacy.</p></div><div className="leadershipProfileGrid">{team.map((m,i)=><article className="leadershipProfile" key={m.name}><figure><img src={m.image} alt={m.name}/><figcaption><span>{String(i+1).padStart(2,'0')}</span><b>{m.unit}</b></figcaption></figure><div className="leadershipProfileCopy"><span>{m.role}</span><h3>{m.name}</h3><p>{m.bio}</p><a className="leadershipLinkedin" href={m.linkedin} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={15}/></a></div></article>)}</div></section>
  <section className="leadershipDisciplines"><div className="leadershipSectionHead compact"><span>HOW LEADERSHIP OPERATES</span><h2>Institutional strength comes from connected disciplines.</h2></div><div className="leadershipDisciplineGrid"><article><b>01</b><h3>Technology</h3><p>Translate climate challenges into useful digital systems, accessible tools and scalable infrastructure.</p></article><article><b>02</b><h3>Research</h3><p>Ground decisions in gender-responsive evidence, economics, community data and measurable learning.</p></article><article><b>03</b><h3>Programs</h3><p>Turn strategy into credible learning, community and adaptation programmes that women can use and sustain.</p></article><article><b>04</b><h3>Advocacy</h3><p>Move women’s climate leadership into public narratives, policy conversations and global partnership spaces.</p></article></div></section>
  <section className="leadershipImpact"><div><span>INSTITUTIONAL IMPACT</span><h2>Scaling women-led research and adaptation into wider climate influence.</h2></div><div className="leadershipImpactProof"><article><strong>Knowledge</strong><p>Community intelligence is documented, analysed and protected.</p></article><article><strong>Systems</strong><p>Technology makes access, coordination and evidence easier to scale.</p></article><article><strong>Leadership</strong><p>Women move from programme participation into visible decision-making roles.</p></article><article><strong>Partnership</strong><p>Institutions can plug into a credible women-led climate ecosystem.</p></article></div></section>
  <section className="leadershipPartner" id="leadership-partner"><div><span>PARTNERSHIP INVITATION</span><h2>Invest in the future of climate leadership.</h2><p>Join global stakeholders working to scale women-led adaptation, research, technology and community resilience across Africa.</p><a href="mailto:womatead@gmail.com">womatead@gmail.com</a></div><form onSubmit={submit}><input name="name" required placeholder="Name / organisation"/><input name="email" required type="email" placeholder="Email address"/><select name="interest" defaultValue=""><option value="" disabled>Area of interest</option><option>Strategic partnership</option><option>Research collaboration</option><option>Programme partnership</option><option>Technology collaboration</option><option>Funding / investment</option><option>Speaking / advocacy</option></select><textarea name="message" placeholder="What would you like to build with WOMATE?"/><button className="pill lime" disabled={status==='sending'}>{status==='sending'?'Sending…':'Initiate partnership'}</button>{status==='sent'&&<small>Thank you. Your enquiry is ready for the WOMATE team.</small>}{status==='error'&&<small className="formError">We could not send this yet. Please email womatead@gmail.com.</small>}</form></section>
 </main></>
}



const WOMATEER_FORM=import.meta.env.VITE_WOMATEER_FORM_EMBED_URL||'https://docs.google.com/forms/d/e/1FAIpQLSe6MZY9sqaYTHzYu1-gm53MbHQIwh8UiA40akKWjubQhXDFpw/viewform?embedded=true';
const WOMATEER_INQUIRY_ENDPOINT=import.meta.env.VITE_WOMATEER_INQUIRY_ENDPOINT||'';
const womateerRoles=[
 {n:'01',title:'Visual Strategist',role:'Graphic Designer',desc:'Shape the visual language of the movement. Translate purpose, dignity and impact into compelling design that strengthens WOMATE’s identity and amplifies women’s voices.',skills:['Brand systems','Campaign design','Editorial storytelling']},
 {n:'02',title:'Digital Systems Lead',role:'Developer',desc:'Design and maintain the digital platforms that power our programmes. Build accessible, reliable infrastructure that connects communities, partners and ideas.',skills:['Web systems','Accessibility','Digital operations']},
 {n:'03',title:'Impact Storyteller',role:'Social Media & Video Lead',desc:'Craft narratives that move beyond awareness into action. Produce ethical, high-quality content that communicates WOMATE’s mission clearly and globally.',skills:['Social media','Video','Impact narratives']},
 {n:'04',title:'Community Impact Lead',role:'Community Engagement Coordinator',desc:'Serve as the bridge between strategy and grassroots action. Coordinate programmes, partnerships and outreach that translate vision into measurable impact.',skills:['Community engagement','Coordination','Partnership delivery']}
];
function WomateerPage(){
 const rolesRef=useRef(null);const[applyOpen,setApplyOpen]=useState(false);const[status,setStatus]=useState('');
 const goRoles=()=>rolesRef.current?.scrollIntoView({behavior:'smooth',block:'start'});
 const submitInquiry=async(e)=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setStatus('sending');try{if(!WOMATEER_INQUIRY_ENDPOINT){window.location.href=`mailto:womatead@gmail.com?subject=${encodeURIComponent('WOMATEER enquiry — '+(data.name||''))}&body=${encodeURIComponent(`Name: ${data.name||''}\nEmail: ${data.email||''}\nRole: ${data.role||''}\n\n${data.message||''}`)}`;setStatus('ready');return}const r=await fetch(WOMATEER_INQUIRY_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,source:'WOMATEER'})});if(!r.ok)throw new Error();setStatus('sent');e.currentTarget.reset()}catch{setStatus('error')}};
 return <>
  <section className="hero hero-volunteer"><div className="heroTop"><div className="heroCopy"><h1>Elevate Your Impact as a WOMATEER</h1><div className="actions"><button className="pill lime" onClick={()=>setApplyOpen(true)}>Apply to become a WOMATEER</button><button className="pill ghost" onClick={goRoles}>Explore roles</button></div></div><HeroVisual type="volunteer"/></div></section>
  <main className="womateerPage">
   <section className="womateerIntro"><span>WOMATEER · 2026 COHORT</span><div><h2>Where purpose meets professional excellence.</h2><p>WOMATEER is WOMATE’s skill-driven volunteer ecosystem for professionals who want their expertise to create measurable climate and social impact. This is not volunteering as an add-on. It is structured contribution—designers, developers, storytellers and community coordinators working alongside a women-led climate organisation.</p></div></section>
   <section className="womateerRoles" ref={rolesRef}><div className="womateerSectionHead"><span>OPEN PATHWAYS</span><h2>Four disciplines. One shared mission.</h2><p>Choose the pathway that best matches the professional skill you can contribute consistently.</p></div><div className="womateerRoleGrid">{womateerRoles.map(r=><article key={r.n}><div className="womateerRoleTop"><span>{r.n}</span><small>{r.role}</small></div><h3>{r.title}</h3><p>{r.desc}</p><div className="womateerSkills">{r.skills.map(x=><span key={x}>{x}</span>)}</div><button onClick={()=>setApplyOpen(true)}>Apply for this pathway</button></article>)}</div></section>
   <section className="womateerStandard"><div><span>WHAT COMMITMENT LOOKS LIKE</span><h2>Bring the skill. Bring the discipline.</h2></div><div className="womateerCommitGrid"><article><b>01</b><h3>Professional contribution</h3><p>You are joining to apply an existing or developing professional skill to live organisational work—not simply observe.</p></article><article><b>02</b><h3>Remote readiness</h3><p>The application checks remote-work comfort and access to a working laptop because collaboration happens across locations.</p></article><article><b>03</b><h3>Reliable availability</h3><p>Applicants identify weekly availability and preferred commitment period so responsibilities can be matched realistically.</p></article><article><b>04</b><h3>Values alignment</h3><p>Strong WOMATEERs combine technical quality with dignity, inclusion, responsible storytelling and respect for communities.</p></article></div></section>
   <section className="womateerJourney"><div className="womateerSectionHead"><span>THE JOURNEY</span><h2>Apply with intention.</h2></div><div className="womateerJourneyGrid"><div><b>01</b><strong>Choose your role</strong><p>Identify where your strongest skill can create value.</p></div><div><b>02</b><strong>Submit your application</strong><p>Share your experience, availability and practical working preferences.</p></div><div><b>03</b><strong>Alignment review</strong><p>WOMATE reviews fit across skills, needs, commitment and values.</p></div><div><b>04</b><strong>Contribute to live work</strong><p>Selected WOMATEERs join a collaborative, values-led working ecosystem.</p></div></div><button className="pill lime" onClick={()=>setApplyOpen(true)}>Start your application</button></section>
   <section className="womateerWhy"><div className="womateerWhyMark">W</div><div><span>WHY WOMATEER</span><h2>Meaningful work should leave evidence.</h2><p>Your contribution should strengthen a programme, system, story, campaign or community process. WOMATEER is designed around work that can be seen, used and built upon.</p></div><div className="womateerProof"><span>Climate resilience</span><span>Women’s empowerment</span><span>Social equity</span><span>Community leadership</span></div></section>
   <section className="womateerInquiry"><div><span>BEFORE YOU APPLY</span><h2>Need to clarify fit?</h2><p>If you have a specialist skill or an application question that does not fit the four pathways cleanly, contact the WOMATE team.</p></div><form onSubmit={submitInquiry}><input name="name" required placeholder="Full name"/><input name="email" type="email" required placeholder="Email address"/><select name="role"><option value="">Area of interest</option>{womateerRoles.map(r=><option key={r.title}>{r.title}</option>)}<option>Other specialist skill</option></select><textarea name="message" required placeholder="Tell us briefly what you can contribute or what you need clarified."/><button className="pill darkbtn" disabled={status==='sending'}>{status==='sending'?'Sending…':'Send enquiry'}</button>{status==='sent'&&<small>Thank you. Your enquiry has been received.</small>}{status==='ready'&&<small>Your email app has been opened with the enquiry prepared.</small>}{status==='error'&&<small>Submission failed. Please try again.</small>}</form></section>
  </main>
  {applyOpen&&<div className="womateerModal" role="dialog" aria-modal="true" aria-label="WOMATEER application"><button className="womateerBackdrop" onClick={()=>setApplyOpen(false)} aria-label="Close application"/><div className="womateerModalPanel"><div className="womateerModalHead"><div><span>WOMATEER 2026</span><h2>Apply with Intention</h2><p>Complete the secure WOMATE volunteer recruitment form.</p></div><button onClick={()=>setApplyOpen(false)} aria-label="Close"><X/></button></div><iframe src={WOMATEER_FORM} title="WOMATE Volunteer Recruitment Form">Loading…</iframe></div></div>}
 </>
}

const FUNDING_INTEREST_ENDPOINT=import.meta.env.VITE_FUNDING_INTEREST_ENDPOINT||'';
function FundingPage(){
 const[open,setOpen]=useState(false),[status,setStatus]=useState('');
 const submit=async e=>{e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form).entries());setStatus('sending');
 if(FUNDING_INTEREST_ENDPOINT){try{let r=await fetch(FUNDING_INTEREST_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,programme:'WOMATE 2027 Funding Interest'})});if(!r.ok)throw 0;setStatus('sent');form.reset()}catch{setStatus('error')}return}
 const subject=encodeURIComponent('WOMATE 2027 Funding Interest');const body=encodeURIComponent(`Name: ${data.name}\nEmail: ${data.email}\nCountry: ${data.country}\nVenture stage: ${data.stage}\nClimate focus: ${data.focus}\n\n${data.note||''}`);window.location.href=`mailto:womatead@gmail.com?subject=${subject}&body=${body}`;setStatus('ready')};
 return <><section className="hero fundingHero"><div className="heroTop"><div className="heroCopy"><span className="fundingKicker">FUNDING SUPPORT · NEXT CYCLE</span><h1>Build a stronger case for climate capital.</h1><p>Grant-readiness support for African women founders building credible climate initiatives.</p><div className="actions"><button className="pill lime" onClick={()=>setOpen(true)}>Register interest · 2027</button><button className="pill ghost" onClick={()=>document.getElementById('funding-support')?.scrollIntoView({behavior:'smooth'})}>Explore support</button></div></div><div className="fundingOrb fundingHeroArtwork"><img src="/assets/hero/funding.png" alt="WOMATE funding support"/></div></div></section>
 <main className="fundingPage">
 <section className="fundingClosed"><b>2026 CYCLE · CLOSED</b><p>The 2026 support programme has concluded. Expired registration dates, fees, payment routes and application forms are no longer presented as active.</p></section>
 <section className="fundingIntro" id="funding-support"><span>BEYOND ONE DEADLINE</span><h2>Funding readiness should outlive a single grant call.</h2><p>The next phase keeps the useful foundations of WOMATE’s previous support—professional review, application streamlining, grant-writing capacity, technical readiness and community access—while preparing founders for future opportunities.</p></section>
 <section className="fundingSupportGrid">{[
 ['01','READINESS DIAGNOSTIC','Understand what is fundable now, what evidence is missing, and what to strengthen before a call opens.'],
 ['02','APPLICATION REVIEW','Improve clarity, alignment, completeness and competitive positioning before submission.'],
 ['03','GRANT WRITING CAPACITY','Frame the problem, solution, outcomes, budget logic and evidence with greater confidence.'],
 ['04','DOCUMENTATION','Prepare reusable materials funders repeatedly request instead of rebuilding from zero.'],
 ['05','FOUNDER POSITIONING','Connect climate impact, gender responsiveness, traction and implementation capacity into one credible case.'],
 ['06','COMMUNITY ACCESS','Learn alongside women building climate solutions and exchange useful funding intelligence and peer support.']
 ].map(([n,h,d])=><article key={n}><span>{n}</span><h3>{h}</h3><p>{d}</p></article>)}</section>
 <section className="fundingRegister"><div><span>THE 2027 REGISTER</span><h2>Register now. Apply when the right opportunity opens.</h2></div><div className="fundingSteps"><p><b>01 · SIGNAL INTEREST</b><br/>Tell WOMATE what you are building and what kind of capital you are preparing for.</p><p><b>02 · BUILD READINESS</b><br/>Use the waiting period to strengthen evidence, documentation and your funding narrative.</p><p><b>03 · RECEIVE CONFIRMED UPDATES</b><br/>WOMATE can contact registered founders when relevant 2027 support or opportunities are confirmed.</p></div></section>
 <section className="fundingCTA"><span>2027 · REGISTER OF INTEREST</span><h2>Do not wait for the deadline to start getting ready.</h2><p>This is an interest register—not a grant application and not a promise of funding.</p><button className="pill lime" onClick={()=>setOpen(true)}>Register interest</button></section>
 </main>
 {open&&<div className="formModal" role="dialog" aria-modal="true"><button className="formBackdrop" onClick={()=>setOpen(false)}/><div className="fundingForm"><button className="fundingClose" onClick={()=>setOpen(false)}>×</button><span>WOMATE · 2027</span><h2>Funding interest register</h2><p>Leave the essentials so WOMATE can share confirmed 2027 funding-support information when available.</p><form onSubmit={submit}><input required name="name" placeholder="Full name"/><input required name="email" type="email" placeholder="Email"/><input required name="country" placeholder="Country"/><select required name="stage" defaultValue=""><option value="" disabled>Venture / project stage</option><option>Idea / pre-launch</option><option>Early stage</option><option>Operating / revenue</option><option>Growth stage</option><option>Community / nonprofit project</option></select><input required name="focus" placeholder="Climate focus"/><textarea name="note" placeholder="What are you preparing to fund?"/><label className="fundingConsent"><input required type="checkbox"/> I agree to receive relevant WOMATE funding-support updates.</label><button className="pill darkbtn" disabled={status==='sending'}>{status==='sending'?'Submitting…':'Join 2027 interest register'}</button>{status==='sent'&&<small>Interest recorded. Thank you.</small>}{status==='ready'&&<small>Your email app has opened with your registration details.</small>}{status==='error'&&<small>Could not submit. Please try again.</small>}</form></div></div>}
 </>}
function Standard({p}){const d=details[p.type],g=pageGallery[p.type]||pageGallery.she;return <><Hero p={p}/><main id="content"><section className="programmeIntro"><div><h3>{d.title}</h3></div><div><p className="lead">Built for credibility in the room and usefulness on the ground. WOMATE combines rigorous thinking with accessible delivery so women can move from participation to influence.</p><div className="miniProof"><ShieldCheck/> Africa-rooted · evidence-led · community-built</div></div></section><section className="galleryTriptych"><figure className="gBig"><img src={g[0]}/><figcaption>WOMATE · {p.k}</figcaption></figure><figure><img src={g[1]}/></figure><figure><img src={g[2]}/></figure></section><section className="featureList">{d.items.map((x,i)=><div className="feature" key={x}><span>0{i+1}</span><h4>{x}</h4><ArrowUpRight/></div>)}</section>{p.type==='she'&&<section className="certificateScene"><div><h3>Learning should leave women with proof, practice and a stronger next step.</h3><p>Structured learning, applied reflection and visible evidence of completion.</p></div><img src="/assets/img/cert.svg"/></section>}{p.type==='leadership'&&<LeadershipFaces/>}{p.type==='honours'&&<Honours/>}{p.type==='merch'&&<Store/>}<section className="ctaBand"><div><h3>{d.aside}</h3></div><Link to="/circle" className="pill lime">Start here <ArrowUpRight/></Link></section>{['funding','volunteer','honours','circle'].includes(p.type)&&<Application type={p.type}/>}<Partner/></main></>}
function LeadershipFaces(){return <section className="leadershipFaces">{[['phillipa-aidoo.png','Phillipa Aidoo'],['asaa.jpeg','Asaa Gyebi-Adjei'],['ruby-damenshie-brown.jpg','Ruby Damenshie-Brown'],['h.jpg','Hamza Abubakar']].map(([im,n])=><article key={n}><img src={'/assets/img/team/'+im}/><div><span>WOMATE LEADERSHIP</span><h4>{n}</h4></div></article>)}</section>}
const MERCH_CHECKOUT_URL=import.meta.env.VITE_MERCH_CHECKOUT_URL||'';
const MERCH_ORDER_ENDPOINT=import.meta.env.VITE_MERCH_ORDER_ENDPOINT||'';
const merchProducts=[
 {id:'core-white',name:'Core White',price:60,front:'/assets/img/merch/12.png',back:'/assets/img/merch/15.png',copy:'A clean white WOMATE tee carrying the Women in Climate identity across the chest and the climate-action statement across the back.'},
 {id:'deep-green',name:'Deep Green',price:60,front:'/assets/img/merch/13.png',back:'/assets/img/merch/14.png',copy:'The deep-green WOMATE tee: a stronger field colour with the core identity in front and the climate-action statement behind.'}
];
function MerchandisePage(){
 const [product,setProduct]=useState(merchProducts[0]);
 const [view,setView]=useState('front');
 const [size,setSize]=useState('M');
 const [qty,setQty]=useState(1);
 const [checkoutOpen,setCheckoutOpen]=useState(false);
 const [status,setStatus]=useState('idle');
 const total=product.price*qty;
 const choose=(p)=>{setProduct(p);setView('front');setQty(1)};
 const pay=()=>{
   if(MERCH_CHECKOUT_URL){const u=new URL(MERCH_CHECKOUT_URL,window.location.origin);u.searchParams.set('product',product.name);u.searchParams.set('size',size);u.searchParams.set('quantity',String(qty));u.searchParams.set('amount',String(total));window.open(u.toString(),'_blank','noopener,noreferrer');return}
   setCheckoutOpen(true);
 };
 const submit=async(e)=>{e.preventDefault();const form=new FormData(e.currentTarget);const payload=Object.fromEntries(form.entries());Object.assign(payload,{product:product.name,size,quantity:qty,total});
   if(!MERCH_ORDER_ENDPOINT){const subject=encodeURIComponent('WOMATE Vault order — '+product.name);const body=encodeURIComponent(`Product: ${product.name}\nSize: ${size}\nQuantity: ${qty}\nTotal: GHS ${total}\n\nName: ${payload.name}\nPhone: ${payload.phone}\nDelivery location: ${payload.location}`);window.location.href=`mailto:womatead@gmail.com?subject=${subject}&body=${body}`;setStatus('ready');return}
   try{setStatus('sending');const r=await fetch(MERCH_ORDER_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error();setStatus('sent')}catch{setStatus('error')}
 };
 return <>
  <section className="hero merchHero"><div className="heroTop"><div className="heroCopy"><h1>The Vault.</h1><div className="actions"><button className="pill lime" onClick={()=>document.getElementById('vault-shop')?.scrollIntoView({behavior:'smooth'})}>SHOP THE VAULT</button></div></div><div className="merchHeroStack"><img src="/assets/img/merch/12.png"/><img src="/assets/img/merch/13.png"/></div></div></section>
  <main className="merchPage" id="vault-shop">
   <section className="merchIntro"><span>WOMATE MERCHANDISE</span><div><h2>Wear the work.</h2><p>The Vault carries a small collection of WOMATE objects designed to make the community visible. The first release begins with two signature tees in the organisation’s core colours.</p></div><aside><b>GHS 60</b><small>per T-shirt</small></aside></section>
   <section className="vaultShop">
    <div className="vaultStage"><div className={'vaultImage '+(product.id==='deep-green'?'greenStage':'whiteStage')}><img src={view==='front'?product.front:product.back} alt={`${product.name} WOMATE T-shirt ${view}`}/><span>{view.toUpperCase()}</span></div><div className="vaultViewToggle"><button className={view==='front'?'active':''} onClick={()=>setView('front')}>Front</button><button className={view==='back'?'active':''} onClick={()=>setView('back')}>Back</button></div></div>
    <div className="vaultBuy"><span>THE VAULT · 01</span><h2>WOMATE T-SHIRT</h2><div className="vaultVariants">{merchProducts.map(p=><button key={p.id} className={product.id===p.id?'active':''} onClick={()=>choose(p)}><img src={p.front}/><div><b>{p.name}</b><small>GHS {p.price}</small></div></button>)}</div><p>{product.copy}</p><div className="vaultOption"><label>Size</label><div>{['S','M','L','XL','2XL'].map(x=><button key={x} className={size===x?'active':''} onClick={()=>setSize(x)}>{x}</button>)}</div></div><div className="vaultQty"><label>Quantity</label><div><button onClick={()=>setQty(Math.max(1,qty-1))}>−</button><strong>{qty}</strong><button onClick={()=>setQty(qty+1)}>+</button></div></div><div className="vaultTotal"><span>Total</span><strong>GHS {total}</strong></div><button className="pill lime vaultCheckout" onClick={pay}>BUY NOW <ArrowUpRight size={17}/></button><small className="vaultNote">Final fulfilment and delivery details are confirmed during checkout.</small></div>
   </section>
   <section className="vaultDetails"><article><span>01</span><h3>Two colours. One statement.</h3><p>Core White and Deep Green carry the same WOMATE identity with contrasting front and back treatments.</p></article><article><span>02</span><h3>Made to represent.</h3><p>For members, alumni, partners and supporters who want to carry the work beyond an event or programme.</p></article><article><span>03</span><h3>Small-batch release.</h3><p>The Vault starts deliberately small. Availability can be managed from your live fulfilment and payment workflow.</p></article></section>
  </main>
  {checkoutOpen&&<div className="vaultModal" role="dialog" aria-modal="true"><button className="vaultModalBackdrop" onClick={()=>setCheckoutOpen(false)} aria-label="Close"/><div className="vaultModalPanel"><div className="vaultModalHead"><div><span>THE VAULT</span><h2>Purchase request</h2></div><button onClick={()=>setCheckoutOpen(false)}><X/></button></div><div className="vaultOrderSummary"><img src={product.front}/><div><b>{product.name}</b><span>Size {size} · Qty {qty}</span><strong>GHS {total}</strong></div></div><form onSubmit={submit}><input name="name" required placeholder="Full name"/><input name="email" type="email" required placeholder="Email address"/><input name="phone" required placeholder="Phone / WhatsApp number"/><input name="location" required placeholder="Delivery city / location"/><textarea name="note" placeholder="Order note (optional)"/><button className="pill darkbtn" disabled={status==='sending'}>{status==='sending'?'Sending…':'Continue order'}</button>{status==='sent'&&<small>Order request received.</small>}{status==='ready'&&<small>Your email app has been opened with the order details.</small>}{status==='error'&&<small>Could not send the order. Please try again.</small>}</form></div></div>}
 </>
}
function Store(){return null}
function Application({type}){return <section className="application"><div><h3>{type==='honours'?'Tell us whose work deserves to be seen.':'Your next step starts here.'}</h3><p>Complete the short form. WOMATE will review your submission and follow up through the contact details you provide.</p></div><form onSubmit={e=>{e.preventDefault();alert('Submission received.')}}><input required placeholder="Full name"/><input required type="email" placeholder="Email address"/><input placeholder="Country"/><textarea placeholder="Tell us briefly about your interest"/><button className="pill darkbtn">Submit <ArrowUpRight/></button></form></section>}
function Footer(){return <footer className="globalFooter"><div className="footerLead"><div className="footerIdentity"><img src="/assets/img/logo.svg"/><h3>Driving inclusive climate action through sustainable technology and community leadership.</h3></div><div className="footerAction"><span>BUILD WITH WOMATE</span><p>Partner with a women-led climate ecosystem connecting knowledge, evidence, community and leadership across Africa.</p><a href="mailto:womatead@gmail.com" className="footerCta">Start a conversation <ArrowUpRight size={18}/></a></div></div><div className="footerDirectory"><div className="footerOffice"><span className="footerLabel">GLOBAL NETWORK</span><strong>Accra, Ghana<br/>Africa · connected globally</strong><a href="mailto:womatead@gmail.com">womatead@gmail.com</a><a href="https://www.linkedin.com/company/womeninclimategh" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={13}/></a></div><div><span className="footerLabel">PROGRAMMES</span><Link to="/she-leads">She Leads</Link><Link to="/wok-action">WoK—Action</Link><Link to="/circle">The WOMATE Circle</Link><Link to="/research">Research</Link><Link to="/resilient-minds">Resilient Minds</Link><Link to="/honours">Climate Honours</Link></div><div><span className="footerLabel">ORGANISATION</span><Link to="/leadership">Our organisation</Link><Link to="/funding">Funding support</Link><Link to="/womateer">WOMATEER</Link><Link to="/merchandise">The Vault</Link></div><div><span className="footerLabel">TAKE PART</span><Link to="/circle">Join the community</Link><Link to="/honours">Nominate a leader</Link><Link to="/womateer">Volunteer</Link><a href="mailto:womatead@gmail.com">Partner with WOMATE</a></div></div><div className="footerBottom"><span>© 2026 WOMATE · Women in Climate</span><div><span>Knowledge</span><span>Technology</span><span>Community</span></div><span>African women leading climate action.</span></div></footer>}
function App(){let path=window.location.pathname.replace(/\/$/,'')||'/';let p=pages[path]||pages['/'];useEffect(()=>window.scrollTo(0,0),[]);return <><Header/>{p.type==='home'?<Home/>:p.type==='she'?<SheLeads/>:p.type==='wok'?<WokAction/>:p.type==='research'?<ResearchPage/>:p.type==='circle'?<CirclePage/>:p.type==='minds'?<ResilientMinds/>:p.type==='honours'?<HonoursPage/>:p.type==='leadership'?<LeadershipPage/>:p.type==='volunteer'?<WomateerPage/>:p.type==='merch'?<MerchandisePage/>:p.type==='funding'?<FundingPage/>:<Standard p={p}/>}<Footer/></>}
createRoot(document.getElementById('root')).render(<App/>);
